// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: api/calendars/calendar/v1alpha1/event.proto

package calendarv1alpha1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "github.com/jcfug8/daylear/server/genapi/api/types"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	latlng "google.golang.org/genproto/googleapis/type/latlng"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// the main user event
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the name of the event
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// the title of the event
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// the start time of the event
	StartTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// the end time of the event
	EndTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// the description of the event
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	// the location of the event
	Location *latlng.LatLng `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	// the url of the event
	Uri string `protobuf:"bytes,7,opt,name=uri,proto3" json:"uri,omitempty"`
	// the recurrence rule of the event
	RecurrenceRule string `protobuf:"bytes,8,opt,name=recurrence_rule,json=recurrenceRule,proto3" json:"recurrence_rule,omitempty"`
	// the start time of the event in the set of recurring events that was overidden
	OverridenStartTime *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=overriden_start_time,json=overridenStartTime,proto3" json:"overriden_start_time,omitempty"`
	// the excluded dates of the event
	ExcludedTimes []*timestamppb.Timestamp `protobuf:"bytes,10,rep,name=excluded_times,json=excludedTimes,proto3" json:"excluded_times,omitempty"`
	// the additional dates of the event
	AdditionalTimes []*timestamppb.Timestamp `protobuf:"bytes,11,rep,name=additional_times,json=additionalTimes,proto3" json:"additional_times,omitempty"`
	// the parent event id of the event
	ParentEventId int64 `protobuf:"varint,12,opt,name=parent_event_id,json=parentEventId,proto3" json:"parent_event_id,omitempty"`
	// the alarms of the event
	Alarms        []*Event_Alarm `protobuf:"bytes,13,rep,name=alarms,proto3" json:"alarms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_api_calendars_calendar_v1alpha1_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_api_calendars_calendar_v1alpha1_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_api_calendars_calendar_v1alpha1_event_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Event) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Event) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Event) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *Event) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Event) GetLocation() *latlng.LatLng {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Event) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *Event) GetRecurrenceRule() string {
	if x != nil {
		return x.RecurrenceRule
	}
	return ""
}

func (x *Event) GetOverridenStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.OverridenStartTime
	}
	return nil
}

func (x *Event) GetExcludedTimes() []*timestamppb.Timestamp {
	if x != nil {
		return x.ExcludedTimes
	}
	return nil
}

func (x *Event) GetAdditionalTimes() []*timestamppb.Timestamp {
	if x != nil {
		return x.AdditionalTimes
	}
	return nil
}

func (x *Event) GetParentEventId() int64 {
	if x != nil {
		return x.ParentEventId
	}
	return 0
}

func (x *Event) GetAlarms() []*Event_Alarm {
	if x != nil {
		return x.Alarms
	}
	return nil
}

// CreateEventRequest is the request message for creating an event
type CreateEventRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The parent resource name
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// The event to create
	Event         *Event `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventRequest) Reset() {
	*x = CreateEventRequest{}
	mi := &file_api_calendars_calendar_v1alpha1_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventRequest) ProtoMessage() {}

func (x *CreateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_calendars_calendar_v1alpha1_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventRequest.ProtoReflect.Descriptor instead.
func (*CreateEventRequest) Descriptor() ([]byte, []int) {
	return file_api_calendars_calendar_v1alpha1_event_proto_rawDescGZIP(), []int{1}
}

func (x *CreateEventRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateEventRequest) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

// GetEventRequest is the request message for getting an event
type GetEventRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the event to retrieve
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventRequest) Reset() {
	*x = GetEventRequest{}
	mi := &file_api_calendars_calendar_v1alpha1_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventRequest) ProtoMessage() {}

func (x *GetEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_calendars_calendar_v1alpha1_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventRequest.ProtoReflect.Descriptor instead.
func (*GetEventRequest) Descriptor() ([]byte, []int) {
	return file_api_calendars_calendar_v1alpha1_event_proto_rawDescGZIP(), []int{2}
}

func (x *GetEventRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// ListEventsRequest is the request message for listing events
type ListEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The parent resource name
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// The maximum number of events to return
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// The next_page_token value returned from a previous List request, if any
	PageToken string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// A filter expression that filters events listed in the response
	Filter        string `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsRequest) Reset() {
	*x = ListEventsRequest{}
	mi := &file_api_calendars_calendar_v1alpha1_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsRequest) ProtoMessage() {}

func (x *ListEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_calendars_calendar_v1alpha1_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsRequest.ProtoReflect.Descriptor instead.
func (*ListEventsRequest) Descriptor() ([]byte, []int) {
	return file_api_calendars_calendar_v1alpha1_event_proto_rawDescGZIP(), []int{3}
}

func (x *ListEventsRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListEventsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListEventsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListEventsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

// ListEventsResponse is the response message for listing events
type ListEventsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of events
	Events []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	// Token to retrieve the next page of results, or empty if there are no more results
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsResponse) Reset() {
	*x = ListEventsResponse{}
	mi := &file_api_calendars_calendar_v1alpha1_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsResponse) ProtoMessage() {}

func (x *ListEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_calendars_calendar_v1alpha1_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsResponse.ProtoReflect.Descriptor instead.
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return file_api_calendars_calendar_v1alpha1_event_proto_rawDescGZIP(), []int{4}
}

func (x *ListEventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ListEventsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// UpdateEventRequest is the request message for updating an event
type UpdateEventRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The event to update
	Event *Event `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	// The list of fields to update
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEventRequest) Reset() {
	*x = UpdateEventRequest{}
	mi := &file_api_calendars_calendar_v1alpha1_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventRequest) ProtoMessage() {}

func (x *UpdateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_calendars_calendar_v1alpha1_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventRequest.ProtoReflect.Descriptor instead.
func (*UpdateEventRequest) Descriptor() ([]byte, []int) {
	return file_api_calendars_calendar_v1alpha1_event_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateEventRequest) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *UpdateEventRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// DeleteEventRequest is the request message for deleting an event
type DeleteEventRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the event to delete
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventRequest) Reset() {
	*x = DeleteEventRequest{}
	mi := &file_api_calendars_calendar_v1alpha1_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventRequest) ProtoMessage() {}

func (x *DeleteEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_calendars_calendar_v1alpha1_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventRequest.ProtoReflect.Descriptor instead.
func (*DeleteEventRequest) Descriptor() ([]byte, []int) {
	return file_api_calendars_calendar_v1alpha1_event_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteEventRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// the alarms of the event
type Event_Alarm struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the alarm id
	AlarmId string `protobuf:"bytes,1,opt,name=alarm_id,json=alarmId,proto3" json:"alarm_id,omitempty"`
	// the trigger of the alarm
	Trigger       *Event_Alarm_Trigger `protobuf:"bytes,2,opt,name=trigger,proto3" json:"trigger,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event_Alarm) Reset() {
	*x = Event_Alarm{}
	mi := &file_api_calendars_calendar_v1alpha1_event_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_Alarm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_Alarm) ProtoMessage() {}

func (x *Event_Alarm) ProtoReflect() protoreflect.Message {
	mi := &file_api_calendars_calendar_v1alpha1_event_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_Alarm.ProtoReflect.Descriptor instead.
func (*Event_Alarm) Descriptor() ([]byte, []int) {
	return file_api_calendars_calendar_v1alpha1_event_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Event_Alarm) GetAlarmId() string {
	if x != nil {
		return x.AlarmId
	}
	return ""
}

func (x *Event_Alarm) GetTrigger() *Event_Alarm_Trigger {
	if x != nil {
		return x.Trigger
	}
	return nil
}

// the trigger of the alarm
type Event_Alarm_Trigger struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Trigger:
	//
	//	*Event_Alarm_Trigger_Duration
	//	*Event_Alarm_Trigger_DateTime
	Trigger       isEvent_Alarm_Trigger_Trigger `protobuf_oneof:"trigger"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event_Alarm_Trigger) Reset() {
	*x = Event_Alarm_Trigger{}
	mi := &file_api_calendars_calendar_v1alpha1_event_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_Alarm_Trigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_Alarm_Trigger) ProtoMessage() {}

func (x *Event_Alarm_Trigger) ProtoReflect() protoreflect.Message {
	mi := &file_api_calendars_calendar_v1alpha1_event_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_Alarm_Trigger.ProtoReflect.Descriptor instead.
func (*Event_Alarm_Trigger) Descriptor() ([]byte, []int) {
	return file_api_calendars_calendar_v1alpha1_event_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *Event_Alarm_Trigger) GetTrigger() isEvent_Alarm_Trigger_Trigger {
	if x != nil {
		return x.Trigger
	}
	return nil
}

func (x *Event_Alarm_Trigger) GetDuration() *durationpb.Duration {
	if x != nil {
		if x, ok := x.Trigger.(*Event_Alarm_Trigger_Duration); ok {
			return x.Duration
		}
	}
	return nil
}

func (x *Event_Alarm_Trigger) GetDateTime() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.Trigger.(*Event_Alarm_Trigger_DateTime); ok {
			return x.DateTime
		}
	}
	return nil
}

type isEvent_Alarm_Trigger_Trigger interface {
	isEvent_Alarm_Trigger_Trigger()
}

type Event_Alarm_Trigger_Duration struct {
	// the duration of the alarm
	Duration *durationpb.Duration `protobuf:"bytes,1,opt,name=duration,proto3,oneof"`
}

type Event_Alarm_Trigger_DateTime struct {
	// the date time of the alarm
	DateTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=date_time,json=dateTime,proto3,oneof"`
}

func (*Event_Alarm_Trigger_Duration) isEvent_Alarm_Trigger_Trigger() {}

func (*Event_Alarm_Trigger_DateTime) isEvent_Alarm_Trigger_Trigger() {}

var File_api_calendars_calendar_v1alpha1_event_proto protoreflect.FileDescriptor

const file_api_calendars_calendar_v1alpha1_event_proto_rawDesc = "" +
	"\n" +
	"+api/calendars/calendar/v1alpha1/event.proto\x12\x1fapi.calendars.calendar.v1alpha1\x1a\x1capi/types/access_state.proto\x1a api/types/permission_level.proto\x1a api/types/visibility_level.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\x1egoogle/protobuf/duration.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18google/type/latlng.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x9c\b\n" +
	"\x05Event\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\bR\x04name\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tB\x03\xe0A\x02R\x05title\x12>\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x02R\tstartTime\x12:\n" +
	"\bend_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x02R\aendTime\x12%\n" +
	"\vdescription\x18\x05 \x01(\tB\x03\xe0A\x01R\vdescription\x124\n" +
	"\blocation\x18\x06 \x01(\v2\x13.google.type.LatLngB\x03\xe0A\x01R\blocation\x12\x15\n" +
	"\x03uri\x18\a \x01(\tB\x03\xe0A\x01R\x03uri\x12,\n" +
	"\x0frecurrence_rule\x18\b \x01(\tB\x03\xe0A\x01R\x0erecurrenceRule\x12Q\n" +
	"\x14overriden_start_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x01R\x12overridenStartTime\x12F\n" +
	"\x0eexcluded_times\x18\n" +
	" \x03(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x01R\rexcludedTimes\x12J\n" +
	"\x10additional_times\x18\v \x03(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x01R\x0fadditionalTimes\x12+\n" +
	"\x0fparent_event_id\x18\f \x01(\x03B\x03\xe0A\x01R\rparentEventId\x12I\n" +
	"\x06alarms\x18\r \x03(\v2,.api.calendars.calendar.v1alpha1.Event.AlarmB\x03\xe0A\x01R\x06alarms\x1a\x87\x02\n" +
	"\x05Alarm\x12\x1e\n" +
	"\balarm_id\x18\x01 \x01(\tB\x03\xe0A\x02R\aalarmId\x12S\n" +
	"\atrigger\x18\x02 \x01(\v24.api.calendars.calendar.v1alpha1.Event.Alarm.TriggerB\x03\xe0A\x02R\atrigger\x1a\x88\x01\n" +
	"\aTrigger\x127\n" +
	"\bduration\x18\x01 \x01(\v2\x19.google.protobuf.DurationH\x00R\bduration\x129\n" +
	"\tdate_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\bdateTimeB\t\n" +
	"\atrigger:X\xeaAU\n" +
	"\x1fapi.events.event.v1alpha1/Event\x12#calendars/{calendar}/events/{event}*\x06events2\x05event\"t\n" +
	"\x12CreateEventRequest\x12\x1b\n" +
	"\x06parent\x18\x01 \x01(\tB\x03\xe0A\x02R\x06parent\x12A\n" +
	"\x05event\x18\x02 \x01(\v2&.api.calendars.calendar.v1alpha1.EventB\x03\xe0A\x02R\x05event\"T\n" +
	"\x0fGetEventRequest\x12A\n" +
	"\x04name\x18\x01 \x01(\tB-\xe0A\x02\xfaA'\n" +
	"%api.calendars.calendar.v1alpha1/EventR\x04name\"\xc0\x01\n" +
	"\x11ListEventsRequest\x12H\n" +
	"\x06parent\x18\x01 \x01(\tB0\xe0A\x02\xfaA*\n" +
	"(api.calendars.calendar.v1alpha1/CalendarR\x06parent\x12 \n" +
	"\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01R\bpageSize\x12\"\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tB\x03\xe0A\x01R\tpageToken\x12\x1b\n" +
	"\x06filter\x18\x04 \x01(\tB\x03\xe0A\x01R\x06filter\"|\n" +
	"\x12ListEventsResponse\x12>\n" +
	"\x06events\x18\x01 \x03(\v2&.api.calendars.calendar.v1alpha1.EventR\x06events\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x99\x01\n" +
	"\x12UpdateEventRequest\x12A\n" +
	"\x05event\x18\x01 \x01(\v2&.api.calendars.calendar.v1alpha1.EventB\x03\xe0A\x02R\x05event\x12@\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x01R\n" +
	"updateMask\"W\n" +
	"\x12DeleteEventRequest\x12A\n" +
	"\x04name\x18\x01 \x01(\tB-\xe0A\x02\xfaA'\n" +
	"%api.calendars.calendar.v1alpha1/EventR\x04name2\xaa\n" +
	"\n" +
	"\fEventService\x12\x8c\x02\n" +
	"\vCreateEvent\x123.api.calendars.calendar.v1alpha1.CreateEventRequest\x1a&.api.calendars.calendar.v1alpha1.Event\"\x9f\x01\x92AO\n" +
	"\fEventService\x12\x0fCreate an event\x1a.Creates a new event in the specified calendar.\xdaA\fparent,event\x82\xd3\xe4\x93\x028:\x05event\"//calendars/v1alpha1/{parent=calendars/*}/events\x12\xef\x01\n" +
	"\bGetEvent\x120.api.calendars.calendar.v1alpha1.GetEventRequest\x1a&.api.calendars.calendar.v1alpha1.Event\"\x88\x01\x92AG\n" +
	"\fEventService\x12\fGet an event\x1a)Retrieves details about a specific event.\xdaA\x04name\x82\xd3\xe4\x93\x021\x12//calendars/v1alpha1/{name=calendars/*/events/*}\x12\x83\x02\n" +
	"\n" +
	"ListEvents\x122.api.calendars.calendar.v1alpha1.ListEventsRequest\x1a3.api.calendars.calendar.v1alpha1.ListEventsResponse\"\x8b\x01\x92AH\n" +
	"\fEventService\x12\vList events\x1a+Lists all events in the specified calendar.\xdaA\x06parent\x82\xd3\xe4\x93\x021\x12//calendars/v1alpha1/{parent=calendars/*}/events\x12\x9d\x02\n" +
	"\vUpdateEvent\x123.api.calendars.calendar.v1alpha1.UpdateEventRequest\x1a&.api.calendars.calendar.v1alpha1.Event\"\xb0\x01\x92AU\n" +
	"\fEventService\x12\x0fUpdate an event\x1a4Updates an existing event with the specified fields.\xdaA\x11event,update_mask\x82\xd3\xe4\x93\x02>:\x05event25/calendars/v1alpha1/{event.name=calendars/*/events/*}\x12\xf2\x01\n" +
	"\vDeleteEvent\x123.api.calendars.calendar.v1alpha1.DeleteEventRequest\x1a&.api.calendars.calendar.v1alpha1.Event\"\x85\x01\x92AD\n" +
	"\fEventService\x12\x0fDelete an event\x1a#Deletes an event from the calendar.\xdaA\x04name\x82\xd3\xe4\x93\x021*//calendars/v1alpha1/{name=calendars/*/events/*}B\x85\x03\x92AXZD\n" +
	"B\n" +
	"\n" +
	"BearerAuth\x124\b\x02\x12\x1fBearer token for authentication\x1a\rAuthorization \x02b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\n" +
	"#com.api.calendars.calendar.v1alpha1B\n" +
	"EventProtoP\x01ZXgithub.com/jcfug8/daylear/server/genapi/api/calendars/calendar/v1alpha1;calendarv1alpha1\xa2\x02\x03ACC\xaa\x02\x1fApi.Calendars.Calendar.V1alpha1\xca\x02\x1fApi\\Calendars\\Calendar\\V1alpha1\xe2\x02+Api\\Calendars\\Calendar\\V1alpha1\\GPBMetadata\xea\x02\"Api::Calendars::Calendar::V1alpha1b\x06proto3"

var (
	file_api_calendars_calendar_v1alpha1_event_proto_rawDescOnce sync.Once
	file_api_calendars_calendar_v1alpha1_event_proto_rawDescData []byte
)

func file_api_calendars_calendar_v1alpha1_event_proto_rawDescGZIP() []byte {
	file_api_calendars_calendar_v1alpha1_event_proto_rawDescOnce.Do(func() {
		file_api_calendars_calendar_v1alpha1_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_calendars_calendar_v1alpha1_event_proto_rawDesc), len(file_api_calendars_calendar_v1alpha1_event_proto_rawDesc)))
	})
	return file_api_calendars_calendar_v1alpha1_event_proto_rawDescData
}

var file_api_calendars_calendar_v1alpha1_event_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_calendars_calendar_v1alpha1_event_proto_goTypes = []any{
	(*Event)(nil),                 // 0: api.calendars.calendar.v1alpha1.Event
	(*CreateEventRequest)(nil),    // 1: api.calendars.calendar.v1alpha1.CreateEventRequest
	(*GetEventRequest)(nil),       // 2: api.calendars.calendar.v1alpha1.GetEventRequest
	(*ListEventsRequest)(nil),     // 3: api.calendars.calendar.v1alpha1.ListEventsRequest
	(*ListEventsResponse)(nil),    // 4: api.calendars.calendar.v1alpha1.ListEventsResponse
	(*UpdateEventRequest)(nil),    // 5: api.calendars.calendar.v1alpha1.UpdateEventRequest
	(*DeleteEventRequest)(nil),    // 6: api.calendars.calendar.v1alpha1.DeleteEventRequest
	(*Event_Alarm)(nil),           // 7: api.calendars.calendar.v1alpha1.Event.Alarm
	(*Event_Alarm_Trigger)(nil),   // 8: api.calendars.calendar.v1alpha1.Event.Alarm.Trigger
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
	(*latlng.LatLng)(nil),         // 10: google.type.LatLng
	(*fieldmaskpb.FieldMask)(nil), // 11: google.protobuf.FieldMask
	(*durationpb.Duration)(nil),   // 12: google.protobuf.Duration
}
var file_api_calendars_calendar_v1alpha1_event_proto_depIdxs = []int32{
	9,  // 0: api.calendars.calendar.v1alpha1.Event.start_time:type_name -> google.protobuf.Timestamp
	9,  // 1: api.calendars.calendar.v1alpha1.Event.end_time:type_name -> google.protobuf.Timestamp
	10, // 2: api.calendars.calendar.v1alpha1.Event.location:type_name -> google.type.LatLng
	9,  // 3: api.calendars.calendar.v1alpha1.Event.overriden_start_time:type_name -> google.protobuf.Timestamp
	9,  // 4: api.calendars.calendar.v1alpha1.Event.excluded_times:type_name -> google.protobuf.Timestamp
	9,  // 5: api.calendars.calendar.v1alpha1.Event.additional_times:type_name -> google.protobuf.Timestamp
	7,  // 6: api.calendars.calendar.v1alpha1.Event.alarms:type_name -> api.calendars.calendar.v1alpha1.Event.Alarm
	0,  // 7: api.calendars.calendar.v1alpha1.CreateEventRequest.event:type_name -> api.calendars.calendar.v1alpha1.Event
	0,  // 8: api.calendars.calendar.v1alpha1.ListEventsResponse.events:type_name -> api.calendars.calendar.v1alpha1.Event
	0,  // 9: api.calendars.calendar.v1alpha1.UpdateEventRequest.event:type_name -> api.calendars.calendar.v1alpha1.Event
	11, // 10: api.calendars.calendar.v1alpha1.UpdateEventRequest.update_mask:type_name -> google.protobuf.FieldMask
	8,  // 11: api.calendars.calendar.v1alpha1.Event.Alarm.trigger:type_name -> api.calendars.calendar.v1alpha1.Event.Alarm.Trigger
	12, // 12: api.calendars.calendar.v1alpha1.Event.Alarm.Trigger.duration:type_name -> google.protobuf.Duration
	9,  // 13: api.calendars.calendar.v1alpha1.Event.Alarm.Trigger.date_time:type_name -> google.protobuf.Timestamp
	1,  // 14: api.calendars.calendar.v1alpha1.EventService.CreateEvent:input_type -> api.calendars.calendar.v1alpha1.CreateEventRequest
	2,  // 15: api.calendars.calendar.v1alpha1.EventService.GetEvent:input_type -> api.calendars.calendar.v1alpha1.GetEventRequest
	3,  // 16: api.calendars.calendar.v1alpha1.EventService.ListEvents:input_type -> api.calendars.calendar.v1alpha1.ListEventsRequest
	5,  // 17: api.calendars.calendar.v1alpha1.EventService.UpdateEvent:input_type -> api.calendars.calendar.v1alpha1.UpdateEventRequest
	6,  // 18: api.calendars.calendar.v1alpha1.EventService.DeleteEvent:input_type -> api.calendars.calendar.v1alpha1.DeleteEventRequest
	0,  // 19: api.calendars.calendar.v1alpha1.EventService.CreateEvent:output_type -> api.calendars.calendar.v1alpha1.Event
	0,  // 20: api.calendars.calendar.v1alpha1.EventService.GetEvent:output_type -> api.calendars.calendar.v1alpha1.Event
	4,  // 21: api.calendars.calendar.v1alpha1.EventService.ListEvents:output_type -> api.calendars.calendar.v1alpha1.ListEventsResponse
	0,  // 22: api.calendars.calendar.v1alpha1.EventService.UpdateEvent:output_type -> api.calendars.calendar.v1alpha1.Event
	0,  // 23: api.calendars.calendar.v1alpha1.EventService.DeleteEvent:output_type -> api.calendars.calendar.v1alpha1.Event
	19, // [19:24] is the sub-list for method output_type
	14, // [14:19] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_api_calendars_calendar_v1alpha1_event_proto_init() }
func file_api_calendars_calendar_v1alpha1_event_proto_init() {
	if File_api_calendars_calendar_v1alpha1_event_proto != nil {
		return
	}
	file_api_calendars_calendar_v1alpha1_event_proto_msgTypes[8].OneofWrappers = []any{
		(*Event_Alarm_Trigger_Duration)(nil),
		(*Event_Alarm_Trigger_DateTime)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_calendars_calendar_v1alpha1_event_proto_rawDesc), len(file_api_calendars_calendar_v1alpha1_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_calendars_calendar_v1alpha1_event_proto_goTypes,
		DependencyIndexes: file_api_calendars_calendar_v1alpha1_event_proto_depIdxs,
		MessageInfos:      file_api_calendars_calendar_v1alpha1_event_proto_msgTypes,
	}.Build()
	File_api_calendars_calendar_v1alpha1_event_proto = out.File
	file_api_calendars_calendar_v1alpha1_event_proto_goTypes = nil
	file_api_calendars_calendar_v1alpha1_event_proto_depIdxs = nil
}
