- included_paths:
    - 'api/**/*'
  disabled_rules:
    - 'core::0191::java-multiple-files'
    - 'core::0191::java-outer-classname'
    - 'core::0191::java-package'
- included_paths:
    - 'api/types/*'
  disabled_rules:
    - 'core::0215::versioned-packages'
- included_paths:
    - 'api/meals/recipe/v1alpha1/recipe.proto'
    - 'api/users/user/v1alpha1/user.proto'
    - 'api/circles/circle/v1alpha1/circle.proto'
    - 'api/calendars/calendar/v1alpha1/calendar.proto'
    - 'api/calendars/calendar/v1alpha1/event.proto'
    - 'api/calendars/calendar/v1alpha1/event_recipe.proto'
    - 'api/lists/list/v1alpha1/list.proto'
    - 'api/lists/list/v1alpha1/list_access.proto'
    - 'api/lists/list/v1alpha1/list_item_completion.proto'
    - 'api/lists/list/v1alpha1/list_item.proto'
    - 'api/lists/list/v1alpha1/list_section.proto'
  disabled_rules:
   - 'core::0133::request-id-field'
   - 'core::0132::http-uri-parent'
   - 'core::0133::http-uri-parent'
   - 'core::0133::request-parent-behavior'
   - 'core::0132::request-parent-behavior'