// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: api/users/user/v1alpha1/access_key.proto

package userv1alpha1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "github.com/jcfug8/daylear/server/genapi/api/types"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This represents the data about a user's access key
type AccessKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the access key
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The title of the access key
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// The description of the access key
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// The access key
	UnencryptedAccessKey string `protobuf:"bytes,4,opt,name=unencrypted_access_key,json=unencryptedAccessKey,proto3" json:"unencrypted_access_key,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AccessKey) Reset() {
	*x = AccessKey{}
	mi := &file_api_users_user_v1alpha1_access_key_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessKey) ProtoMessage() {}

func (x *AccessKey) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_user_v1alpha1_access_key_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessKey.ProtoReflect.Descriptor instead.
func (*AccessKey) Descriptor() ([]byte, []int) {
	return file_api_users_user_v1alpha1_access_key_proto_rawDescGZIP(), []int{0}
}

func (x *AccessKey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AccessKey) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AccessKey) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AccessKey) GetUnencryptedAccessKey() string {
	if x != nil {
		return x.UnencryptedAccessKey
	}
	return ""
}

// The request to create an access key
type CreateAccessKeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// parent
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// The access key to create
	AccessKey     *AccessKey `protobuf:"bytes,2,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccessKeyRequest) Reset() {
	*x = CreateAccessKeyRequest{}
	mi := &file_api_users_user_v1alpha1_access_key_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccessKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccessKeyRequest) ProtoMessage() {}

func (x *CreateAccessKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_user_v1alpha1_access_key_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccessKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateAccessKeyRequest) Descriptor() ([]byte, []int) {
	return file_api_users_user_v1alpha1_access_key_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAccessKeyRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateAccessKeyRequest) GetAccessKey() *AccessKey {
	if x != nil {
		return x.AccessKey
	}
	return nil
}

// The request to delete an access key
type DeleteAccessKeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccessKeyRequest) Reset() {
	*x = DeleteAccessKeyRequest{}
	mi := &file_api_users_user_v1alpha1_access_key_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccessKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccessKeyRequest) ProtoMessage() {}

func (x *DeleteAccessKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_user_v1alpha1_access_key_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccessKeyRequest.ProtoReflect.Descriptor instead.
func (*DeleteAccessKeyRequest) Descriptor() ([]byte, []int) {
	return file_api_users_user_v1alpha1_access_key_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteAccessKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The request to get an access key
type GetAccessKeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccessKeyRequest) Reset() {
	*x = GetAccessKeyRequest{}
	mi := &file_api_users_user_v1alpha1_access_key_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccessKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccessKeyRequest) ProtoMessage() {}

func (x *GetAccessKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_user_v1alpha1_access_key_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccessKeyRequest.ProtoReflect.Descriptor instead.
func (*GetAccessKeyRequest) Descriptor() ([]byte, []int) {
	return file_api_users_user_v1alpha1_access_key_proto_rawDescGZIP(), []int{3}
}

func (x *GetAccessKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The request to list access keys
type ListAccessKeysRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// parent
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// The filter to apply to the list
	Filter string `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	// The page size to apply to the list
	PageSize int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// The page token to apply to the list
	PageToken     string `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccessKeysRequest) Reset() {
	*x = ListAccessKeysRequest{}
	mi := &file_api_users_user_v1alpha1_access_key_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccessKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccessKeysRequest) ProtoMessage() {}

func (x *ListAccessKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_user_v1alpha1_access_key_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccessKeysRequest.ProtoReflect.Descriptor instead.
func (*ListAccessKeysRequest) Descriptor() ([]byte, []int) {
	return file_api_users_user_v1alpha1_access_key_proto_rawDescGZIP(), []int{4}
}

func (x *ListAccessKeysRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListAccessKeysRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListAccessKeysRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAccessKeysRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// The response to list access keys
type ListAccessKeysResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of access keys
	AccessKeys []*AccessKey `protobuf:"bytes,1,rep,name=access_keys,json=accessKeys,proto3" json:"access_keys,omitempty"`
	// The next page token
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccessKeysResponse) Reset() {
	*x = ListAccessKeysResponse{}
	mi := &file_api_users_user_v1alpha1_access_key_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccessKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccessKeysResponse) ProtoMessage() {}

func (x *ListAccessKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_user_v1alpha1_access_key_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccessKeysResponse.ProtoReflect.Descriptor instead.
func (*ListAccessKeysResponse) Descriptor() ([]byte, []int) {
	return file_api_users_user_v1alpha1_access_key_proto_rawDescGZIP(), []int{5}
}

func (x *ListAccessKeysResponse) GetAccessKeys() []*AccessKey {
	if x != nil {
		return x.AccessKeys
	}
	return nil
}

func (x *ListAccessKeysResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// The request to update an access key
type UpdateAccessKeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// access key
	AccessKey *AccessKey `protobuf:"bytes,1,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	// update mask
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccessKeyRequest) Reset() {
	*x = UpdateAccessKeyRequest{}
	mi := &file_api_users_user_v1alpha1_access_key_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccessKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccessKeyRequest) ProtoMessage() {}

func (x *UpdateAccessKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_user_v1alpha1_access_key_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccessKeyRequest.ProtoReflect.Descriptor instead.
func (*UpdateAccessKeyRequest) Descriptor() ([]byte, []int) {
	return file_api_users_user_v1alpha1_access_key_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateAccessKeyRequest) GetAccessKey() *AccessKey {
	if x != nil {
		return x.AccessKey
	}
	return nil
}

func (x *UpdateAccessKeyRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

var File_api_users_user_v1alpha1_access_key_proto protoreflect.FileDescriptor

const file_api_users_user_v1alpha1_access_key_proto_rawDesc = "" +
	"\n" +
	"(api/users/user/v1alpha1/access_key.proto\x12\x17api.users.user.v1alpha1\x1a\x1dapi/types/accept_target.proto\x1a\x1capi/types/access_state.proto\x1a api/types/permission_level.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x86\x02\n" +
	"\tAccessKey\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\bR\x04name\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tB\x03\xe0A\x02R\x05title\x12%\n" +
	"\vdescription\x18\x03 \x01(\tB\x03\xe0A\x01R\vdescription\x129\n" +
	"\x16unencrypted_access_key\x18\x04 \x01(\tB\x03\xe0A\x03R\x14unencryptedAccessKey:c\xeaA`\n" +
	"!api.users.user.v1alpha1/AccessKey\x12$users/{user}/accessKeys/{access_key}*\n" +
	"accessKeys2\taccessKey\"\x9e\x01\n" +
	"\x16CreateAccessKeyRequest\x12<\n" +
	"\x06parent\x18\x01 \x01(\tB$\xe0A\x02\xfaA\x1e\n" +
	"\x1capi.users.user.v1alpha1/UserR\x06parent\x12F\n" +
	"\n" +
	"access_key\x18\x02 \x01(\v2\".api.users.user.v1alpha1.AccessKeyB\x03\xe0A\x02R\taccessKey\"W\n" +
	"\x16DeleteAccessKeyRequest\x12=\n" +
	"\x04name\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n" +
	"!api.users.user.v1alpha1/AccessKeyR\x04name\"T\n" +
	"\x13GetAccessKeyRequest\x12=\n" +
	"\x04name\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n" +
	"!api.users.user.v1alpha1/AccessKeyR\x04name\"\xb8\x01\n" +
	"\x15ListAccessKeysRequest\x12<\n" +
	"\x06parent\x18\x01 \x01(\tB$\xe0A\x02\xfaA\x1e\n" +
	"\x1capi.users.user.v1alpha1/UserR\x06parent\x12\x1b\n" +
	"\x06filter\x18\x02 \x01(\tB\x03\xe0A\x01R\x06filter\x12 \n" +
	"\tpage_size\x18\x03 \x01(\x05B\x03\xe0A\x01R\bpageSize\x12\"\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tB\x03\xe0A\x01R\tpageToken\"\x85\x01\n" +
	"\x16ListAccessKeysResponse\x12C\n" +
	"\vaccess_keys\x18\x01 \x03(\v2\".api.users.user.v1alpha1.AccessKeyR\n" +
	"accessKeys\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xa2\x01\n" +
	"\x16UpdateAccessKeyRequest\x12F\n" +
	"\n" +
	"access_key\x18\x01 \x01(\v2\".api.users.user.v1alpha1.AccessKeyB\x03\xe0A\x02R\taccessKey\x12@\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x01R\n" +
	"updateMask2\xc4\v\n" +
	"\x10AccessKeyService\x12\xb6\x02\n" +
	"\x0fCreateAccessKey\x12/.api.users.user.v1alpha1.CreateAccessKeyRequest\x1a\".api.users.user.v1alpha1.AccessKey\"\xcd\x01\x92Aw\n" +
	"\x10AccessKeyService\x12%Grant a user or user access to a user\x1a<Grants a user or user a specific permission level to a user.\xdaA\x11parent,access_key\x82\xd3\xe4\x93\x029:\n" +
	"access_key\"+/users/v1alpha1/{parent=users/*}/accessKeys\x12\xee\x01\n" +
	"\x0fDeleteAccessKey\x12/.api.users.user.v1alpha1.DeleteAccessKeyRequest\x1a\x16.google.protobuf.Empty\"\x91\x01\x92AT\n" +
	"\x10AccessKeyService\x12\x18Delete a user access key\x1a&Removes a user's or user's access key.\xdaA\x04name\x82\xd3\xe4\x93\x02-*+/users/v1alpha1/{name=users/*/accessKeys/*}\x12\xfe\x01\n" +
	"\fGetAccessKey\x12,.api.users.user.v1alpha1.GetAccessKeyRequest\x1a\".api.users.user.v1alpha1.AccessKey\"\x9b\x01\x92A^\n" +
	"\x10AccessKeyService\x12\x15Get a user access key\x1a3Retrieves details about a specific user access key.\xdaA\x04name\x82\xd3\xe4\x93\x02-\x12+/users/v1alpha1/{name=users/*/accessKeys/*}\x12\xff\x01\n" +
	"\x0eListAccessKeys\x12..api.users.user.v1alpha1.ListAccessKeysRequest\x1a/.api.users.user.v1alpha1.ListAccessKeysResponse\"\x8b\x01\x92AL\n" +
	"\x10AccessKeyService\x12\x15List user access keys\x1a!Lists all access keys a user has.\xdaA\x06parent\x82\xd3\xe4\x93\x02-\x12+/users/v1alpha1/{parent=users/*}/accessKeys\x12\xaf\x02\n" +
	"\x0fUpdateAccessKey\x12/.api.users.user.v1alpha1.UpdateAccessKeyRequest\x1a\".api.users.user.v1alpha1.AccessKey\"\xc6\x01\x92A`\n" +
	"\x10AccessKeyService\x12\x18Update a user access key\x1a2Updates a user's access key title and description.\xdaA\x16access_key,update_mask\x82\xd3\xe4\x93\x02D:\n" +
	"access_key26/users/v1alpha1/{access_key.name=users/*/accessKeys/*}\x1aQ\x92AN\x12\x15Access Key management\x1a5\n" +
	"\x19Daylear API Documentation\x12\x18https://daylear.com/docsB\xd5\x02\x92AXZD\n" +
	"B\n" +
	"\n" +
	"BearerAuth\x124\b\x02\x12\x1fBearer token for authentication\x1a\rAuthorization \x02b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\n" +
	"\x1bcom.api.users.user.v1alpha1B\x0eAccessKeyProtoP\x01ZLgithub.com/jcfug8/daylear/server/genapi/api/users/user/v1alpha1;userv1alpha1\xa2\x02\x03AUU\xaa\x02\x17Api.Users.User.V1alpha1\xca\x02\x17Api\\Users\\User\\V1alpha1\xe2\x02#Api\\Users\\User\\V1alpha1\\GPBMetadata\xea\x02\x1aApi::Users::User::V1alpha1b\x06proto3"

var (
	file_api_users_user_v1alpha1_access_key_proto_rawDescOnce sync.Once
	file_api_users_user_v1alpha1_access_key_proto_rawDescData []byte
)

func file_api_users_user_v1alpha1_access_key_proto_rawDescGZIP() []byte {
	file_api_users_user_v1alpha1_access_key_proto_rawDescOnce.Do(func() {
		file_api_users_user_v1alpha1_access_key_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_users_user_v1alpha1_access_key_proto_rawDesc), len(file_api_users_user_v1alpha1_access_key_proto_rawDesc)))
	})
	return file_api_users_user_v1alpha1_access_key_proto_rawDescData
}

var file_api_users_user_v1alpha1_access_key_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_users_user_v1alpha1_access_key_proto_goTypes = []any{
	(*AccessKey)(nil),              // 0: api.users.user.v1alpha1.AccessKey
	(*CreateAccessKeyRequest)(nil), // 1: api.users.user.v1alpha1.CreateAccessKeyRequest
	(*DeleteAccessKeyRequest)(nil), // 2: api.users.user.v1alpha1.DeleteAccessKeyRequest
	(*GetAccessKeyRequest)(nil),    // 3: api.users.user.v1alpha1.GetAccessKeyRequest
	(*ListAccessKeysRequest)(nil),  // 4: api.users.user.v1alpha1.ListAccessKeysRequest
	(*ListAccessKeysResponse)(nil), // 5: api.users.user.v1alpha1.ListAccessKeysResponse
	(*UpdateAccessKeyRequest)(nil), // 6: api.users.user.v1alpha1.UpdateAccessKeyRequest
	(*fieldmaskpb.FieldMask)(nil),  // 7: google.protobuf.FieldMask
	(*emptypb.Empty)(nil),          // 8: google.protobuf.Empty
}
var file_api_users_user_v1alpha1_access_key_proto_depIdxs = []int32{
	0, // 0: api.users.user.v1alpha1.CreateAccessKeyRequest.access_key:type_name -> api.users.user.v1alpha1.AccessKey
	0, // 1: api.users.user.v1alpha1.ListAccessKeysResponse.access_keys:type_name -> api.users.user.v1alpha1.AccessKey
	0, // 2: api.users.user.v1alpha1.UpdateAccessKeyRequest.access_key:type_name -> api.users.user.v1alpha1.AccessKey
	7, // 3: api.users.user.v1alpha1.UpdateAccessKeyRequest.update_mask:type_name -> google.protobuf.FieldMask
	1, // 4: api.users.user.v1alpha1.AccessKeyService.CreateAccessKey:input_type -> api.users.user.v1alpha1.CreateAccessKeyRequest
	2, // 5: api.users.user.v1alpha1.AccessKeyService.DeleteAccessKey:input_type -> api.users.user.v1alpha1.DeleteAccessKeyRequest
	3, // 6: api.users.user.v1alpha1.AccessKeyService.GetAccessKey:input_type -> api.users.user.v1alpha1.GetAccessKeyRequest
	4, // 7: api.users.user.v1alpha1.AccessKeyService.ListAccessKeys:input_type -> api.users.user.v1alpha1.ListAccessKeysRequest
	6, // 8: api.users.user.v1alpha1.AccessKeyService.UpdateAccessKey:input_type -> api.users.user.v1alpha1.UpdateAccessKeyRequest
	0, // 9: api.users.user.v1alpha1.AccessKeyService.CreateAccessKey:output_type -> api.users.user.v1alpha1.AccessKey
	8, // 10: api.users.user.v1alpha1.AccessKeyService.DeleteAccessKey:output_type -> google.protobuf.Empty
	0, // 11: api.users.user.v1alpha1.AccessKeyService.GetAccessKey:output_type -> api.users.user.v1alpha1.AccessKey
	5, // 12: api.users.user.v1alpha1.AccessKeyService.ListAccessKeys:output_type -> api.users.user.v1alpha1.ListAccessKeysResponse
	0, // 13: api.users.user.v1alpha1.AccessKeyService.UpdateAccessKey:output_type -> api.users.user.v1alpha1.AccessKey
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_users_user_v1alpha1_access_key_proto_init() }
func file_api_users_user_v1alpha1_access_key_proto_init() {
	if File_api_users_user_v1alpha1_access_key_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_users_user_v1alpha1_access_key_proto_rawDesc), len(file_api_users_user_v1alpha1_access_key_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_users_user_v1alpha1_access_key_proto_goTypes,
		DependencyIndexes: file_api_users_user_v1alpha1_access_key_proto_depIdxs,
		MessageInfos:      file_api_users_user_v1alpha1_access_key_proto_msgTypes,
	}.Build()
	File_api_users_user_v1alpha1_access_key_proto = out.File
	file_api_users_user_v1alpha1_access_key_proto_goTypes = nil
	file_api_users_user_v1alpha1_access_key_proto_depIdxs = nil
}
