// Code generated by protoc-gen-typescript-http. DO NOT EDIT.
/* eslint-disable camelcase */
// @ts-nocheck

// the permission levels
export type PermissionLevel =
  // the permission is not specified
  | "PERMISSION_LEVEL_UNSPECIFIED"
  // the permission is read
  | "PERMISSION_LEVEL_READ"
  // the permission is write
  | "PERMISSION_LEVEL_WRITE"
  // the permission is admin
  | "PERMISSION_LEVEL_ADMIN";

// @@protoc_insertion_point(typescript-http-eof)
