// Code generated by protoc-gen-typescript-http. DO NOT EDIT.
/* eslint-disable camelcase */
// @ts-nocheck

// the permission levels
export type PermissionLevel =
  // the permission is not specified
  | "RESOURCE_PERMISSION_UNSPECIFIED"
  // the permission is read
  | "RESOURCE_PERMISSION_READ"
  // the permission is write
  | "RESOURCE_PERMISSION_WRITE";

// @@protoc_insertion_point(typescript-http-eof)
