version: '3.8'

services:
  db:
    image: postgres:13.5
    container_name: local_db
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: daylear
      POSTGRES_DB: daylear
    ports:
      - "5432:5432"
    command: >
      -c log_statement=all
      -c logging_collector=on
      -c log_directory=/var/log/postgresql
      -c log_filename=postgressql.log

  s3:
    image: adobe/s3mock
    container_name: local_s3
    environment:
      initialBuckets: daylear
      debug: "true"
    ports:
      - "9090:9090" 