// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/circles/circle/v1alpha1/circle_access.proto

package circlev1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	CircleAccessService_CreateAccess_FullMethodName = "/api.circles.circle.v1alpha1.CircleAccessService/CreateAccess"
	CircleAccessService_DeleteAccess_FullMethodName = "/api.circles.circle.v1alpha1.CircleAccessService/DeleteAccess"
	CircleAccessService_GetAccess_FullMethodName    = "/api.circles.circle.v1alpha1.CircleAccessService/GetAccess"
	CircleAccessService_ListAccesses_FullMethodName = "/api.circles.circle.v1alpha1.CircleAccessService/ListAccesses"
	CircleAccessService_UpdateAccess_FullMethodName = "/api.circles.circle.v1alpha1.CircleAccessService/UpdateAccess"
	CircleAccessService_AcceptAccess_FullMethodName = "/api.circles.circle.v1alpha1.CircleAccessService/AcceptAccess"
)

// CircleAccessServiceClient is the client API for CircleAccessService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The circle recipient list service
type CircleAccessServiceClient interface {
	// Create an access to a circle
	CreateAccess(ctx context.Context, in *CreateAccessRequest, opts ...grpc.CallOption) (*Access, error)
	// Delete an access to a circle
	DeleteAccess(ctx context.Context, in *DeleteAccessRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Get an access to a circle
	GetAccess(ctx context.Context, in *GetAccessRequest, opts ...grpc.CallOption) (*Access, error)
	// List accesses to a circle
	ListAccesses(ctx context.Context, in *ListAccessesRequest, opts ...grpc.CallOption) (*ListAccessesResponse, error)
	// Update an access to a circle
	UpdateAccess(ctx context.Context, in *UpdateAccessRequest, opts ...grpc.CallOption) (*Access, error)
	// Accept a circle access
	AcceptAccess(ctx context.Context, in *AcceptAccessRequest, opts ...grpc.CallOption) (*Access, error)
}

type circleAccessServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCircleAccessServiceClient(cc grpc.ClientConnInterface) CircleAccessServiceClient {
	return &circleAccessServiceClient{cc}
}

func (c *circleAccessServiceClient) CreateAccess(ctx context.Context, in *CreateAccessRequest, opts ...grpc.CallOption) (*Access, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Access)
	err := c.cc.Invoke(ctx, CircleAccessService_CreateAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *circleAccessServiceClient) DeleteAccess(ctx context.Context, in *DeleteAccessRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, CircleAccessService_DeleteAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *circleAccessServiceClient) GetAccess(ctx context.Context, in *GetAccessRequest, opts ...grpc.CallOption) (*Access, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Access)
	err := c.cc.Invoke(ctx, CircleAccessService_GetAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *circleAccessServiceClient) ListAccesses(ctx context.Context, in *ListAccessesRequest, opts ...grpc.CallOption) (*ListAccessesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAccessesResponse)
	err := c.cc.Invoke(ctx, CircleAccessService_ListAccesses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *circleAccessServiceClient) UpdateAccess(ctx context.Context, in *UpdateAccessRequest, opts ...grpc.CallOption) (*Access, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Access)
	err := c.cc.Invoke(ctx, CircleAccessService_UpdateAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *circleAccessServiceClient) AcceptAccess(ctx context.Context, in *AcceptAccessRequest, opts ...grpc.CallOption) (*Access, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Access)
	err := c.cc.Invoke(ctx, CircleAccessService_AcceptAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CircleAccessServiceServer is the server API for CircleAccessService service.
// All implementations must embed UnimplementedCircleAccessServiceServer
// for forward compatibility.
//
// The circle recipient list service
type CircleAccessServiceServer interface {
	// Create an access to a circle
	CreateAccess(context.Context, *CreateAccessRequest) (*Access, error)
	// Delete an access to a circle
	DeleteAccess(context.Context, *DeleteAccessRequest) (*emptypb.Empty, error)
	// Get an access to a circle
	GetAccess(context.Context, *GetAccessRequest) (*Access, error)
	// List accesses to a circle
	ListAccesses(context.Context, *ListAccessesRequest) (*ListAccessesResponse, error)
	// Update an access to a circle
	UpdateAccess(context.Context, *UpdateAccessRequest) (*Access, error)
	// Accept a circle access
	AcceptAccess(context.Context, *AcceptAccessRequest) (*Access, error)
	mustEmbedUnimplementedCircleAccessServiceServer()
}

// UnimplementedCircleAccessServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCircleAccessServiceServer struct{}

func (UnimplementedCircleAccessServiceServer) CreateAccess(context.Context, *CreateAccessRequest) (*Access, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAccess not implemented")
}
func (UnimplementedCircleAccessServiceServer) DeleteAccess(context.Context, *DeleteAccessRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAccess not implemented")
}
func (UnimplementedCircleAccessServiceServer) GetAccess(context.Context, *GetAccessRequest) (*Access, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccess not implemented")
}
func (UnimplementedCircleAccessServiceServer) ListAccesses(context.Context, *ListAccessesRequest) (*ListAccessesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAccesses not implemented")
}
func (UnimplementedCircleAccessServiceServer) UpdateAccess(context.Context, *UpdateAccessRequest) (*Access, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAccess not implemented")
}
func (UnimplementedCircleAccessServiceServer) AcceptAccess(context.Context, *AcceptAccessRequest) (*Access, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcceptAccess not implemented")
}
func (UnimplementedCircleAccessServiceServer) mustEmbedUnimplementedCircleAccessServiceServer() {}
func (UnimplementedCircleAccessServiceServer) testEmbeddedByValue()                             {}

// UnsafeCircleAccessServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CircleAccessServiceServer will
// result in compilation errors.
type UnsafeCircleAccessServiceServer interface {
	mustEmbedUnimplementedCircleAccessServiceServer()
}

func RegisterCircleAccessServiceServer(s grpc.ServiceRegistrar, srv CircleAccessServiceServer) {
	// If the following call pancis, it indicates UnimplementedCircleAccessServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CircleAccessService_ServiceDesc, srv)
}

func _CircleAccessService_CreateAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CircleAccessServiceServer).CreateAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CircleAccessService_CreateAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CircleAccessServiceServer).CreateAccess(ctx, req.(*CreateAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CircleAccessService_DeleteAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CircleAccessServiceServer).DeleteAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CircleAccessService_DeleteAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CircleAccessServiceServer).DeleteAccess(ctx, req.(*DeleteAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CircleAccessService_GetAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CircleAccessServiceServer).GetAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CircleAccessService_GetAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CircleAccessServiceServer).GetAccess(ctx, req.(*GetAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CircleAccessService_ListAccesses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAccessesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CircleAccessServiceServer).ListAccesses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CircleAccessService_ListAccesses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CircleAccessServiceServer).ListAccesses(ctx, req.(*ListAccessesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CircleAccessService_UpdateAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CircleAccessServiceServer).UpdateAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CircleAccessService_UpdateAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CircleAccessServiceServer).UpdateAccess(ctx, req.(*UpdateAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CircleAccessService_AcceptAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CircleAccessServiceServer).AcceptAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CircleAccessService_AcceptAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CircleAccessServiceServer).AcceptAccess(ctx, req.(*AcceptAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CircleAccessService_ServiceDesc is the grpc.ServiceDesc for CircleAccessService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CircleAccessService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.circles.circle.v1alpha1.CircleAccessService",
	HandlerType: (*CircleAccessServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccess",
			Handler:    _CircleAccessService_CreateAccess_Handler,
		},
		{
			MethodName: "DeleteAccess",
			Handler:    _CircleAccessService_DeleteAccess_Handler,
		},
		{
			MethodName: "GetAccess",
			Handler:    _CircleAccessService_GetAccess_Handler,
		},
		{
			MethodName: "ListAccesses",
			Handler:    _CircleAccessService_ListAccesses_Handler,
		},
		{
			MethodName: "UpdateAccess",
			Handler:    _CircleAccessService_UpdateAccess_Handler,
		},
		{
			MethodName: "AcceptAccess",
			Handler:    _CircleAccessService_AcceptAccess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/circles/circle/v1alpha1/circle_access.proto",
}
