// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/circles/circle/v1alpha1/circle_access.proto

package circlev1alpha1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	types "github.com/jcfug8/daylear/server/genapi/api/types"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// the status of the access
type Access_State int32

const (
	// This status should never get used.
	Access_STATE_UNSPECIFIED Access_State = 0
	// The access is pending and can either be accepted or deleted.
	Access_STATE_PENDING Access_State = 100
	// The access is accepted and can be deleted.
	Access_STATE_ACCEPTED Access_State = 200
)

// Enum value maps for Access_State.
var (
	Access_State_name = map[int32]string{
		0:   "STATE_UNSPECIFIED",
		100: "STATE_PENDING",
		200: "STATE_ACCEPTED",
	}
	Access_State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"STATE_PENDING":     100,
		"STATE_ACCEPTED":    200,
	}
)

func (x Access_State) Enum() *Access_State {
	p := new(Access_State)
	*p = x
	return p
}

func (x Access_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Access_State) Descriptor() protoreflect.EnumDescriptor {
	return file_api_circles_circle_v1alpha1_circle_access_proto_enumTypes[0].Descriptor()
}

func (Access_State) Type() protoreflect.EnumType {
	return &file_api_circles_circle_v1alpha1_circle_access_proto_enumTypes[0]
}

func (x Access_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Access_State.Descriptor instead.
func (Access_State) EnumDescriptor() ([]byte, []int) {
	return file_api_circles_circle_v1alpha1_circle_access_proto_rawDescGZIP(), []int{0, 0}
}

// This represents the data about a user's access to a circle
type Access struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the access
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// the name of the requesting user
	Requester string `protobuf:"bytes,2,opt,name=requester,proto3" json:"requester,omitempty"`
	// the name of the receiving user
	Recipient string `protobuf:"bytes,3,opt,name=recipient,proto3" json:"recipient,omitempty"`
	// the permission level of the access
	Level types.PermissionLevel `protobuf:"varint,4,opt,name=level,proto3,enum=api.types.PermissionLevel" json:"level,omitempty"`
	// the status of the access
	State         Access_State `protobuf:"varint,5,opt,name=state,proto3,enum=api.circles.circle.v1alpha1.Access_State" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Access) Reset() {
	*x = Access{}
	mi := &file_api_circles_circle_v1alpha1_circle_access_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Access) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Access) ProtoMessage() {}

func (x *Access) ProtoReflect() protoreflect.Message {
	mi := &file_api_circles_circle_v1alpha1_circle_access_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Access.ProtoReflect.Descriptor instead.
func (*Access) Descriptor() ([]byte, []int) {
	return file_api_circles_circle_v1alpha1_circle_access_proto_rawDescGZIP(), []int{0}
}

func (x *Access) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Access) GetRequester() string {
	if x != nil {
		return x.Requester
	}
	return ""
}

func (x *Access) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *Access) GetLevel() types.PermissionLevel {
	if x != nil {
		return x.Level
	}
	return types.PermissionLevel(0)
}

func (x *Access) GetState() Access_State {
	if x != nil {
		return x.State
	}
	return Access_STATE_UNSPECIFIED
}

// The request to create an access to a circle
type CreateAccessRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// parent
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// The access to create
	Access        *Access `protobuf:"bytes,2,opt,name=access,proto3" json:"access,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccessRequest) Reset() {
	*x = CreateAccessRequest{}
	mi := &file_api_circles_circle_v1alpha1_circle_access_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccessRequest) ProtoMessage() {}

func (x *CreateAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_circles_circle_v1alpha1_circle_access_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccessRequest.ProtoReflect.Descriptor instead.
func (*CreateAccessRequest) Descriptor() ([]byte, []int) {
	return file_api_circles_circle_v1alpha1_circle_access_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAccessRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateAccessRequest) GetAccess() *Access {
	if x != nil {
		return x.Access
	}
	return nil
}

// The request to delete an access to a circle
type DeleteAccessRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccessRequest) Reset() {
	*x = DeleteAccessRequest{}
	mi := &file_api_circles_circle_v1alpha1_circle_access_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccessRequest) ProtoMessage() {}

func (x *DeleteAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_circles_circle_v1alpha1_circle_access_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccessRequest.ProtoReflect.Descriptor instead.
func (*DeleteAccessRequest) Descriptor() ([]byte, []int) {
	return file_api_circles_circle_v1alpha1_circle_access_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteAccessRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The request to get an access to a circle
type GetAccessRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccessRequest) Reset() {
	*x = GetAccessRequest{}
	mi := &file_api_circles_circle_v1alpha1_circle_access_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccessRequest) ProtoMessage() {}

func (x *GetAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_circles_circle_v1alpha1_circle_access_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccessRequest.ProtoReflect.Descriptor instead.
func (*GetAccessRequest) Descriptor() ([]byte, []int) {
	return file_api_circles_circle_v1alpha1_circle_access_proto_rawDescGZIP(), []int{3}
}

func (x *GetAccessRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The request to list accesses to a circle
type ListAccessesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// parent
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// The filter to apply to the list
	Filter string `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	// The page size to apply to the list
	PageSize int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// The page token to apply to the list
	PageToken     string `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccessesRequest) Reset() {
	*x = ListAccessesRequest{}
	mi := &file_api_circles_circle_v1alpha1_circle_access_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccessesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccessesRequest) ProtoMessage() {}

func (x *ListAccessesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_circles_circle_v1alpha1_circle_access_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccessesRequest.ProtoReflect.Descriptor instead.
func (*ListAccessesRequest) Descriptor() ([]byte, []int) {
	return file_api_circles_circle_v1alpha1_circle_access_proto_rawDescGZIP(), []int{4}
}

func (x *ListAccessesRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListAccessesRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListAccessesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAccessesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// The response to list accesses to a circle
type ListAccessesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of accesses
	Accesses []*Access `protobuf:"bytes,1,rep,name=accesses,proto3" json:"accesses,omitempty"`
	// The next page token
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccessesResponse) Reset() {
	*x = ListAccessesResponse{}
	mi := &file_api_circles_circle_v1alpha1_circle_access_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccessesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccessesResponse) ProtoMessage() {}

func (x *ListAccessesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_circles_circle_v1alpha1_circle_access_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccessesResponse.ProtoReflect.Descriptor instead.
func (*ListAccessesResponse) Descriptor() ([]byte, []int) {
	return file_api_circles_circle_v1alpha1_circle_access_proto_rawDescGZIP(), []int{5}
}

func (x *ListAccessesResponse) GetAccesses() []*Access {
	if x != nil {
		return x.Accesses
	}
	return nil
}

func (x *ListAccessesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// The request to update an access to a circle
type UpdateAccessRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// access
	Access *Access `protobuf:"bytes,1,opt,name=access,proto3" json:"access,omitempty"`
	// update mask
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccessRequest) Reset() {
	*x = UpdateAccessRequest{}
	mi := &file_api_circles_circle_v1alpha1_circle_access_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccessRequest) ProtoMessage() {}

func (x *UpdateAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_circles_circle_v1alpha1_circle_access_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccessRequest.ProtoReflect.Descriptor instead.
func (*UpdateAccessRequest) Descriptor() ([]byte, []int) {
	return file_api_circles_circle_v1alpha1_circle_access_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateAccessRequest) GetAccess() *Access {
	if x != nil {
		return x.Access
	}
	return nil
}

func (x *UpdateAccessRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// The request to accept an access to a circle
type AcceptAccessRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptAccessRequest) Reset() {
	*x = AcceptAccessRequest{}
	mi := &file_api_circles_circle_v1alpha1_circle_access_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptAccessRequest) ProtoMessage() {}

func (x *AcceptAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_circles_circle_v1alpha1_circle_access_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptAccessRequest.ProtoReflect.Descriptor instead.
func (*AcceptAccessRequest) Descriptor() ([]byte, []int) {
	return file_api_circles_circle_v1alpha1_circle_access_proto_rawDescGZIP(), []int{7}
}

func (x *AcceptAccessRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_api_circles_circle_v1alpha1_circle_access_proto protoreflect.FileDescriptor

const file_api_circles_circle_v1alpha1_circle_access_proto_rawDesc = "" +
	"\n" +
	"/api/circles/circle/v1alpha1/circle_access.proto\x12\x1bapi.circles.circle.v1alpha1\x1a api/types/permission_level.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x8b\x03\n" +
	"\x06Access\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\bR\x04name\x12!\n" +
	"\trequester\x18\x02 \x01(\tB\x03\xe0A\x03R\trequester\x12!\n" +
	"\trecipient\x18\x03 \x01(\tB\x03\xe0A\x02R\trecipient\x125\n" +
	"\x05level\x18\x04 \x01(\x0e2\x1a.api.types.PermissionLevelB\x03\xe0A\x02R\x05level\x12D\n" +
	"\x05state\x18\x05 \x01(\x0e2).api.circles.circle.v1alpha1.Access.StateB\x03\xe0A\x03R\x05state\"F\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTATE_PENDING\x10d\x12\x13\n" +
	"\x0eSTATE_ACCEPTED\x10\xc8\x01:]\xeaAZ\n" +
	"\"api.circles.circle.v1alpha1/Access\x12\"circles/{circle}/accesses/{access}*\baccesses2\x06access\"\x9b\x01\n" +
	"\x13CreateAccessRequest\x12B\n" +
	"\x06parent\x18\x01 \x01(\tB*\xe0A\x02\xfaA$\n" +
	"\"api.circles.circle.v1alpha1/CircleR\x06parent\x12@\n" +
	"\x06access\x18\x02 \x01(\v2#.api.circles.circle.v1alpha1.AccessB\x03\xe0A\x02R\x06access\"U\n" +
	"\x13DeleteAccessRequest\x12>\n" +
	"\x04name\x18\x01 \x01(\tB*\xe0A\x02\xfaA$\n" +
	"\"api.circles.circle.v1alpha1/AccessR\x04name\"R\n" +
	"\x10GetAccessRequest\x12>\n" +
	"\x04name\x18\x01 \x01(\tB*\xe0A\x02\xfaA$\n" +
	"\"api.circles.circle.v1alpha1/AccessR\x04name\"\xbc\x01\n" +
	"\x13ListAccessesRequest\x12B\n" +
	"\x06parent\x18\x01 \x01(\tB*\xe0A\x02\xfaA$\n" +
	"\"api.circles.circle.v1alpha1/CircleR\x06parent\x12\x1b\n" +
	"\x06filter\x18\x02 \x01(\tB\x03\xe0A\x01R\x06filter\x12 \n" +
	"\tpage_size\x18\x03 \x01(\x05B\x03\xe0A\x01R\bpageSize\x12\"\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tB\x03\xe0A\x01R\tpageToken\"\x7f\n" +
	"\x14ListAccessesResponse\x12?\n" +
	"\baccesses\x18\x01 \x03(\v2#.api.circles.circle.v1alpha1.AccessR\baccesses\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x99\x01\n" +
	"\x13UpdateAccessRequest\x12@\n" +
	"\x06access\x18\x01 \x01(\v2#.api.circles.circle.v1alpha1.AccessB\x03\xe0A\x02R\x06access\x12@\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x01R\n" +
	"updateMask\"U\n" +
	"\x13AcceptAccessRequest\x12>\n" +
	"\x04name\x18\x01 \x01(\tB*\xe0A\x02\xfaA$\n" +
	"\"api.circles.circle.v1alpha1/AccessR\x04name2\x8f\x12\n" +
	"\x13CircleAccessService\x12\xf5\x02\n" +
	"\fCreateAccess\x120.api.circles.circle.v1alpha1.CreateAccessRequest\x1a#.api.circles.circle.v1alpha1.Access\"\x8d\x02\x92A\xbc\x01\n" +
	"\x13CircleAccessService\x12)Grant a user or circle access to a circle\x1a@Grants a user or circle a specific permission level to a circle.r8\n" +
	"6\n" +
	"\x10X-Daylear-Circle\x12 the name of the circle to act as\x18\x01\xdaA\rparent,access\x82\xd3\xe4\x93\x027:\x06access\"-/circles/v1alpha1/{parent=circles/*}/accesses\x12\xb4\x02\n" +
	"\fDeleteAccess\x120.api.circles.circle.v1alpha1.DeleteAccessRequest\x1a\x16.google.protobuf.Empty\"\xd9\x01\x92A\x99\x01\n" +
	"\x13CircleAccessService\x12\x16Delete a circle access\x1a0Removes a user's or circle's access to a circle.r8\n" +
	"6\n" +
	"\x10X-Daylear-Circle\x12 the name of the circle to act as\x18\x01\xdaA\x04name\x82\xd3\xe4\x93\x02/*-/circles/v1alpha1/{name=circles/*/accesses/*}\x12\xb9\x02\n" +
	"\tGetAccess\x12-.api.circles.circle.v1alpha1.GetAccessRequest\x1a#.api.circles.circle.v1alpha1.Access\"\xd7\x01\x92A\x97\x01\n" +
	"\x13CircleAccessService\x12\x13Get a circle access\x1a1Retrieves details about a specific circle access.r8\n" +
	"6\n" +
	"\x10X-Daylear-Circle\x12 the name of the circle to act as\x18\x01\xdaA\x04name\x82\xd3\xe4\x93\x02/\x12-/circles/v1alpha1/{name=circles/*/accesses/*}\x12\xdc\x03\n" +
	"\fListAccesses\x120.api.circles.circle.v1alpha1.ListAccessesRequest\x1a1.api.circles.circle.v1alpha1.ListAccessesResponse\"\xe6\x02\x92A\xa4\x02\n" +
	"\x13CircleAccessService\x12\x14List circle accesses\x1a\xbc\x01Lists all users and circles with access to a circle. If no circle is provided, the response will only return the accesses for the current user (or circle if the circle header is provided).r8\n" +
	"6\n" +
	"\x10X-Daylear-Circle\x12 the name of the circle to act as\x18\x01\xdaA\x06parent\x82\xd3\xe4\x93\x02/\x12-/circles/v1alpha1/{parent=circles/*}/accesses\x12\xec\x02\n" +
	"\fUpdateAccess\x120.api.circles.circle.v1alpha1.UpdateAccessRequest\x1a#.api.circles.circle.v1alpha1.Access\"\x84\x02\x92A\xa7\x01\n" +
	"\x13CircleAccessService\x12\x16Update a circle access\x1a>Updates the permission level or recipient for a circle access.r8\n" +
	"6\n" +
	"\x10X-Daylear-Circle\x12 the name of the circle to act as\x18\x01\xdaA\x12access,update_mask\x82\xd3\xe4\x93\x02>:\x06access24/circles/v1alpha1/{access.name=circles/*/accesses/*}\x12\xe8\x02\n" +
	"\fAcceptAccess\x120.api.circles.circle.v1alpha1.AcceptAccessRequest\x1a#.api.circles.circle.v1alpha1.Access\"\x80\x02\x92A\xb6\x01\n" +
	"\x13CircleAccessService\x12\x16Accept a circle access\x1aMAccepts a pending circle access, changing its state from PENDING to ACCEPTED.r8\n" +
	"6\n" +
	"\x10X-Daylear-Circle\x12 the name of the circle to act as\x18\x01\xdaA\x04name\x82\xd3\xe4\x93\x029:\x01*\"4/circles/v1alpha1/{name=circles/*/accesses/*}:accept\x1aT\x92AQ\x12\x18Circle Access management\x1a5\n" +
	"\x19Daylear API Documentation\x12\x18https://daylear.com/docsB\xf2\x02\x92AXZD\n" +
	"B\n" +
	"\n" +
	"BearerAuth\x124\b\x02\x12\x1fBearer token for authentication\x1a\rAuthorization \x02b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\n" +
	"\x1fcom.api.circles.circle.v1alpha1B\x11CircleAccessProtoP\x01ZRgithub.com/jcfug8/daylear/server/genapi/api/circles/circle/v1alpha1;circlev1alpha1\xa2\x02\x03ACC\xaa\x02\x1bApi.Circles.Circle.V1alpha1\xca\x02\x1bApi\\Circles\\Circle\\V1alpha1\xe2\x02'Api\\Circles\\Circle\\V1alpha1\\GPBMetadata\xea\x02\x1eApi::Circles::Circle::V1alpha1b\x06proto3"

var (
	file_api_circles_circle_v1alpha1_circle_access_proto_rawDescOnce sync.Once
	file_api_circles_circle_v1alpha1_circle_access_proto_rawDescData []byte
)

func file_api_circles_circle_v1alpha1_circle_access_proto_rawDescGZIP() []byte {
	file_api_circles_circle_v1alpha1_circle_access_proto_rawDescOnce.Do(func() {
		file_api_circles_circle_v1alpha1_circle_access_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_circles_circle_v1alpha1_circle_access_proto_rawDesc), len(file_api_circles_circle_v1alpha1_circle_access_proto_rawDesc)))
	})
	return file_api_circles_circle_v1alpha1_circle_access_proto_rawDescData
}

var file_api_circles_circle_v1alpha1_circle_access_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_circles_circle_v1alpha1_circle_access_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_circles_circle_v1alpha1_circle_access_proto_goTypes = []any{
	(Access_State)(0),             // 0: api.circles.circle.v1alpha1.Access.State
	(*Access)(nil),                // 1: api.circles.circle.v1alpha1.Access
	(*CreateAccessRequest)(nil),   // 2: api.circles.circle.v1alpha1.CreateAccessRequest
	(*DeleteAccessRequest)(nil),   // 3: api.circles.circle.v1alpha1.DeleteAccessRequest
	(*GetAccessRequest)(nil),      // 4: api.circles.circle.v1alpha1.GetAccessRequest
	(*ListAccessesRequest)(nil),   // 5: api.circles.circle.v1alpha1.ListAccessesRequest
	(*ListAccessesResponse)(nil),  // 6: api.circles.circle.v1alpha1.ListAccessesResponse
	(*UpdateAccessRequest)(nil),   // 7: api.circles.circle.v1alpha1.UpdateAccessRequest
	(*AcceptAccessRequest)(nil),   // 8: api.circles.circle.v1alpha1.AcceptAccessRequest
	(types.PermissionLevel)(0),    // 9: api.types.PermissionLevel
	(*fieldmaskpb.FieldMask)(nil), // 10: google.protobuf.FieldMask
	(*emptypb.Empty)(nil),         // 11: google.protobuf.Empty
}
var file_api_circles_circle_v1alpha1_circle_access_proto_depIdxs = []int32{
	9,  // 0: api.circles.circle.v1alpha1.Access.level:type_name -> api.types.PermissionLevel
	0,  // 1: api.circles.circle.v1alpha1.Access.state:type_name -> api.circles.circle.v1alpha1.Access.State
	1,  // 2: api.circles.circle.v1alpha1.CreateAccessRequest.access:type_name -> api.circles.circle.v1alpha1.Access
	1,  // 3: api.circles.circle.v1alpha1.ListAccessesResponse.accesses:type_name -> api.circles.circle.v1alpha1.Access
	1,  // 4: api.circles.circle.v1alpha1.UpdateAccessRequest.access:type_name -> api.circles.circle.v1alpha1.Access
	10, // 5: api.circles.circle.v1alpha1.UpdateAccessRequest.update_mask:type_name -> google.protobuf.FieldMask
	2,  // 6: api.circles.circle.v1alpha1.CircleAccessService.CreateAccess:input_type -> api.circles.circle.v1alpha1.CreateAccessRequest
	3,  // 7: api.circles.circle.v1alpha1.CircleAccessService.DeleteAccess:input_type -> api.circles.circle.v1alpha1.DeleteAccessRequest
	4,  // 8: api.circles.circle.v1alpha1.CircleAccessService.GetAccess:input_type -> api.circles.circle.v1alpha1.GetAccessRequest
	5,  // 9: api.circles.circle.v1alpha1.CircleAccessService.ListAccesses:input_type -> api.circles.circle.v1alpha1.ListAccessesRequest
	7,  // 10: api.circles.circle.v1alpha1.CircleAccessService.UpdateAccess:input_type -> api.circles.circle.v1alpha1.UpdateAccessRequest
	8,  // 11: api.circles.circle.v1alpha1.CircleAccessService.AcceptAccess:input_type -> api.circles.circle.v1alpha1.AcceptAccessRequest
	1,  // 12: api.circles.circle.v1alpha1.CircleAccessService.CreateAccess:output_type -> api.circles.circle.v1alpha1.Access
	11, // 13: api.circles.circle.v1alpha1.CircleAccessService.DeleteAccess:output_type -> google.protobuf.Empty
	1,  // 14: api.circles.circle.v1alpha1.CircleAccessService.GetAccess:output_type -> api.circles.circle.v1alpha1.Access
	6,  // 15: api.circles.circle.v1alpha1.CircleAccessService.ListAccesses:output_type -> api.circles.circle.v1alpha1.ListAccessesResponse
	1,  // 16: api.circles.circle.v1alpha1.CircleAccessService.UpdateAccess:output_type -> api.circles.circle.v1alpha1.Access
	1,  // 17: api.circles.circle.v1alpha1.CircleAccessService.AcceptAccess:output_type -> api.circles.circle.v1alpha1.Access
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_circles_circle_v1alpha1_circle_access_proto_init() }
func file_api_circles_circle_v1alpha1_circle_access_proto_init() {
	if File_api_circles_circle_v1alpha1_circle_access_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_circles_circle_v1alpha1_circle_access_proto_rawDesc), len(file_api_circles_circle_v1alpha1_circle_access_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_circles_circle_v1alpha1_circle_access_proto_goTypes,
		DependencyIndexes: file_api_circles_circle_v1alpha1_circle_access_proto_depIdxs,
		EnumInfos:         file_api_circles_circle_v1alpha1_circle_access_proto_enumTypes,
		MessageInfos:      file_api_circles_circle_v1alpha1_circle_access_proto_msgTypes,
	}.Build()
	File_api_circles_circle_v1alpha1_circle_access_proto = out.File
	file_api_circles_circle_v1alpha1_circle_access_proto_goTypes = nil
	file_api_circles_circle_v1alpha1_circle_access_proto_depIdxs = nil
}
