// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: api/lists/list/v1alpha1/list_item.proto

package listv1alpha1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "github.com/jcfug8/daylear/server/genapi/api/types"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// the main listItem object
type ListItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the name of the listItem
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// the title of the listItem
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// List Section
	ListSection string `protobuf:"bytes,3,opt,name=list_section,json=listSection,proto3" json:"list_section,omitempty"`
	// points
	Points int32 `protobuf:"varint,4,opt,name=points,proto3" json:"points,omitempty"`
	// the recurrence rule of the listItem
	RecurrenceRule string `protobuf:"bytes,5,opt,name=recurrence_rule,json=recurrenceRule,proto3" json:"recurrence_rule,omitempty"`
	// the time the listItem was created (UTC)
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// the time the listItem was last updated (UTC)
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItem) Reset() {
	*x = ListItem{}
	mi := &file_api_lists_list_v1alpha1_list_item_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItem) ProtoMessage() {}

func (x *ListItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_lists_list_v1alpha1_list_item_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItem.ProtoReflect.Descriptor instead.
func (*ListItem) Descriptor() ([]byte, []int) {
	return file_api_lists_list_v1alpha1_list_item_proto_rawDescGZIP(), []int{0}
}

func (x *ListItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ListItem) GetListSection() string {
	if x != nil {
		return x.ListSection
	}
	return ""
}

func (x *ListItem) GetPoints() int32 {
	if x != nil {
		return x.Points
	}
	return 0
}

func (x *ListItem) GetRecurrenceRule() string {
	if x != nil {
		return x.RecurrenceRule
	}
	return ""
}

func (x *ListItem) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *ListItem) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

// the request to create a listItem
type CreateListItemRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the parent of the listItem
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// the listItem to create
	ListItem      *ListItem `protobuf:"bytes,2,opt,name=list_item,json=listItem,proto3" json:"list_item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateListItemRequest) Reset() {
	*x = CreateListItemRequest{}
	mi := &file_api_lists_list_v1alpha1_list_item_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateListItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateListItemRequest) ProtoMessage() {}

func (x *CreateListItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_lists_list_v1alpha1_list_item_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateListItemRequest.ProtoReflect.Descriptor instead.
func (*CreateListItemRequest) Descriptor() ([]byte, []int) {
	return file_api_lists_list_v1alpha1_list_item_proto_rawDescGZIP(), []int{1}
}

func (x *CreateListItemRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateListItemRequest) GetListItem() *ListItem {
	if x != nil {
		return x.ListItem
	}
	return nil
}

// the request to listItem listItems
type ListListItemsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the parent of the listItems
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// returned page
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// used to specify the page token
	PageToken string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// used to specify the filter
	Filter        string `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListListItemsRequest) Reset() {
	*x = ListListItemsRequest{}
	mi := &file_api_lists_list_v1alpha1_list_item_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListListItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListListItemsRequest) ProtoMessage() {}

func (x *ListListItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_lists_list_v1alpha1_list_item_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListListItemsRequest.ProtoReflect.Descriptor instead.
func (*ListListItemsRequest) Descriptor() ([]byte, []int) {
	return file_api_lists_list_v1alpha1_list_item_proto_rawDescGZIP(), []int{2}
}

func (x *ListListItemsRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListListItemsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListListItemsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListListItemsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

// the response to listItem listItems
type ListListItemsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the listItems
	ListItems []*ListItem `protobuf:"bytes,1,rep,name=list_items,json=listItems,proto3" json:"list_items,omitempty"`
	// the next page token
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListListItemsResponse) Reset() {
	*x = ListListItemsResponse{}
	mi := &file_api_lists_list_v1alpha1_list_item_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListListItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListListItemsResponse) ProtoMessage() {}

func (x *ListListItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_lists_list_v1alpha1_list_item_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListListItemsResponse.ProtoReflect.Descriptor instead.
func (*ListListItemsResponse) Descriptor() ([]byte, []int) {
	return file_api_lists_list_v1alpha1_list_item_proto_rawDescGZIP(), []int{3}
}

func (x *ListListItemsResponse) GetListItems() []*ListItem {
	if x != nil {
		return x.ListItems
	}
	return nil
}

func (x *ListListItemsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// the request to update a listItem
type UpdateListItemRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the listItem to update
	ListItem *ListItem `protobuf:"bytes,1,opt,name=list_item,json=listItem,proto3" json:"list_item,omitempty"`
	// the fields to update
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateListItemRequest) Reset() {
	*x = UpdateListItemRequest{}
	mi := &file_api_lists_list_v1alpha1_list_item_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateListItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateListItemRequest) ProtoMessage() {}

func (x *UpdateListItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_lists_list_v1alpha1_list_item_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateListItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateListItemRequest) Descriptor() ([]byte, []int) {
	return file_api_lists_list_v1alpha1_list_item_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateListItemRequest) GetListItem() *ListItem {
	if x != nil {
		return x.ListItem
	}
	return nil
}

func (x *UpdateListItemRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// the request to delete a listItem
type DeleteListItemRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the name of the listItem to delete
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteListItemRequest) Reset() {
	*x = DeleteListItemRequest{}
	mi := &file_api_lists_list_v1alpha1_list_item_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteListItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteListItemRequest) ProtoMessage() {}

func (x *DeleteListItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_lists_list_v1alpha1_list_item_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteListItemRequest.ProtoReflect.Descriptor instead.
func (*DeleteListItemRequest) Descriptor() ([]byte, []int) {
	return file_api_lists_list_v1alpha1_list_item_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteListItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// the request to get a listItem
type GetListItemRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the name of the listItem to get
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListItemRequest) Reset() {
	*x = GetListItemRequest{}
	mi := &file_api_lists_list_v1alpha1_list_item_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListItemRequest) ProtoMessage() {}

func (x *GetListItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_lists_list_v1alpha1_list_item_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListItemRequest.ProtoReflect.Descriptor instead.
func (*GetListItemRequest) Descriptor() ([]byte, []int) {
	return file_api_lists_list_v1alpha1_list_item_proto_rawDescGZIP(), []int{6}
}

func (x *GetListItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_api_lists_list_v1alpha1_list_item_proto protoreflect.FileDescriptor

const file_api_lists_list_v1alpha1_list_item_proto_rawDesc = "" +
	"\n" +
	"'api/lists/list/v1alpha1/list_item.proto\x12\x17api.lists.list.v1alpha1\x1a\x1dapi/types/accept_target.proto\x1a\x1capi/types/access_state.proto\x1a api/types/permission_level.proto\x1a api/types/visibility_level.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x95\x03\n" +
	"\bListItem\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\bR\x04name\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tB\x03\xe0A\x02R\x05title\x12&\n" +
	"\flist_section\x18\x03 \x01(\tB\x03\xe0A\x02R\vlistSection\x12\x1b\n" +
	"\x06points\x18\x04 \x01(\x05B\x03\xe0A\x02R\x06points\x12,\n" +
	"\x0frecurrence_rule\x18\x05 \x01(\tB\x03\xe0A\x01R\x0erecurrenceRule\x12@\n" +
	"\vcreate_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"createTime\x12@\n" +
	"\vupdate_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"updateTime:^\xeaA[\n" +
	" api.lists.list.v1alpha1/ListItem\x12\"lists/{list}/listItems/{list_item}*\tlistItems2\blistItem\"\x9a\x01\n" +
	"\x15CreateListItemRequest\x12<\n" +
	"\x06parent\x18\x01 \x01(\tB$\xe0A\x02\xfaA\x1e\n" +
	"\x1capi.lists/list.v1alpha1/ListR\x06parent\x12C\n" +
	"\tlist_item\x18\x02 \x01(\v2!.api.lists.list.v1alpha1.ListItemB\x03\xe0A\x02R\blistItem\"\xb7\x01\n" +
	"\x14ListListItemsRequest\x12<\n" +
	"\x06parent\x18\x01 \x01(\tB$\xe0A\x02\xfaA\x1e\n" +
	"\x1capi.lists/list.v1alpha1/ListR\x06parent\x12 \n" +
	"\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01R\bpageSize\x12\"\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tB\x03\xe0A\x01R\tpageToken\x12\x1b\n" +
	"\x06filter\x18\x04 \x01(\tB\x03\xe0A\x01R\x06filter\"\x81\x01\n" +
	"\x15ListListItemsResponse\x12@\n" +
	"\n" +
	"list_items\x18\x01 \x03(\v2!.api.lists.list.v1alpha1.ListItemR\tlistItems\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x9e\x01\n" +
	"\x15UpdateListItemRequest\x12C\n" +
	"\tlist_item\x18\x01 \x01(\v2!.api.lists.list.v1alpha1.ListItemB\x03\xe0A\x02R\blistItem\x12@\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x01R\n" +
	"updateMask\"U\n" +
	"\x15DeleteListItemRequest\x12<\n" +
	"\x04name\x18\x01 \x01(\tB(\xe0A\x02\xfaA\"\n" +
	" api.lists.list.v1alpha1/ListItemR\x04name\"R\n" +
	"\x12GetListItemRequest\x12<\n" +
	"\x04name\x18\x01 \x01(\tB(\xe0A\x02\xfaA\"\n" +
	" api.lists.list.v1alpha1/ListItemR\x04name2\xc8\n" +
	"\n" +
	"\x0fListItemService\x12\x90\x02\n" +
	"\x0eCreateListItem\x12..api.lists.list.v1alpha1.CreateListItemRequest\x1a!.api.lists.list.v1alpha1.ListItem\"\xaa\x01\x92AW\n" +
	"\x0fListItemService\x12\x11Create a listItem\x1a1Creates a new listItem with the provided details.\xdaA\x10parent,list_item\x82\xd3\xe4\x93\x027:\tlist_item\"*/lists/v1alpha1/{parent=lists/*}/listItems\x12\xa6\x02\n" +
	"\rListListItems\x12-.api.lists.list.v1alpha1.ListListItemsRequest\x1a..api.lists.list.v1alpha1.ListListItemsResponse\"\xb5\x01\x92Aw\n" +
	"\x0fListItemService\x12\x13ListItem list_items\x1aORetrieves a paginated listItem of listItems. Supports filtering and pagination.\xdaA\x06parent\x82\xd3\xe4\x93\x02,\x12*/lists/v1alpha1/{parent=lists/*}/listItems\x12\x9a\x02\n" +
	"\x0eUpdateListItem\x12..api.lists.list.v1alpha1.UpdateListItemRequest\x1a!.api.lists.list.v1alpha1.ListItem\"\xb4\x01\x92AR\n" +
	"\x0fListItemService\x12\x11Update a listItem\x1a,Updates the details of an existing listItem.\xdaA\x15list_item,update_mask\x82\xd3\xe4\x93\x02A:\tlist_item24/lists/v1alpha1/{list_item.name=lists/*/listItems/*}\x12\xec\x01\n" +
	"\x0eDeleteListItem\x12..api.lists.list.v1alpha1.DeleteListItemRequest\x1a!.api.lists.list.v1alpha1.ListItem\"\x86\x01\x92AJ\n" +
	"\x0fListItemService\x12\x11Delete a listItem\x1a$Deletes a listItem by resource name.\xdaA\x04name\x82\xd3\xe4\x93\x02,**/lists/v1alpha1/{name=lists/*/listItems/*}\x12\xec\x01\n" +
	"\vGetListItem\x12+.api.lists.list.v1alpha1.GetListItemRequest\x1a!.api.lists.list.v1alpha1.ListItem\"\x8c\x01\x92AP\n" +
	"\x0fListItemService\x12\x0eGet a listItem\x1a-Retrieves a single listItem by resource name.\xdaA\x04name\x82\xd3\xe4\x93\x02,\x12*/lists/v1alpha1/{name=lists/*/listItems/*}B\xd6\x02\x92AXZD\n" +
	"B\n" +
	"\n" +
	"BearerAuth\x124\b\x02\x12\x1fBearer token for authentication\x1a\rAuthorization \x02b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\n" +
	"\x1bcom.api.lists.list.v1alpha1B\rListItemProtoP\x01ZLgithub.com/jcfug8/daylear/server/genapi/api/lists/list/v1alpha1;listv1alpha1\xa2\x02\x03ALL\xaa\x02\x17Api.Lists.List.V1alpha1\xca\x02\x18Api\\Lists\\List_\\V1alpha1\xe2\x02$Api\\Lists\\List_\\V1alpha1\\GPBMetadata\xea\x02\x1aApi::Lists::List::V1alpha1b\x06proto3"

var (
	file_api_lists_list_v1alpha1_list_item_proto_rawDescOnce sync.Once
	file_api_lists_list_v1alpha1_list_item_proto_rawDescData []byte
)

func file_api_lists_list_v1alpha1_list_item_proto_rawDescGZIP() []byte {
	file_api_lists_list_v1alpha1_list_item_proto_rawDescOnce.Do(func() {
		file_api_lists_list_v1alpha1_list_item_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_lists_list_v1alpha1_list_item_proto_rawDesc), len(file_api_lists_list_v1alpha1_list_item_proto_rawDesc)))
	})
	return file_api_lists_list_v1alpha1_list_item_proto_rawDescData
}

var file_api_lists_list_v1alpha1_list_item_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_lists_list_v1alpha1_list_item_proto_goTypes = []any{
	(*ListItem)(nil),              // 0: api.lists.list.v1alpha1.ListItem
	(*CreateListItemRequest)(nil), // 1: api.lists.list.v1alpha1.CreateListItemRequest
	(*ListListItemsRequest)(nil),  // 2: api.lists.list.v1alpha1.ListListItemsRequest
	(*ListListItemsResponse)(nil), // 3: api.lists.list.v1alpha1.ListListItemsResponse
	(*UpdateListItemRequest)(nil), // 4: api.lists.list.v1alpha1.UpdateListItemRequest
	(*DeleteListItemRequest)(nil), // 5: api.lists.list.v1alpha1.DeleteListItemRequest
	(*GetListItemRequest)(nil),    // 6: api.lists.list.v1alpha1.GetListItemRequest
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil), // 8: google.protobuf.FieldMask
}
var file_api_lists_list_v1alpha1_list_item_proto_depIdxs = []int32{
	7,  // 0: api.lists.list.v1alpha1.ListItem.create_time:type_name -> google.protobuf.Timestamp
	7,  // 1: api.lists.list.v1alpha1.ListItem.update_time:type_name -> google.protobuf.Timestamp
	0,  // 2: api.lists.list.v1alpha1.CreateListItemRequest.list_item:type_name -> api.lists.list.v1alpha1.ListItem
	0,  // 3: api.lists.list.v1alpha1.ListListItemsResponse.list_items:type_name -> api.lists.list.v1alpha1.ListItem
	0,  // 4: api.lists.list.v1alpha1.UpdateListItemRequest.list_item:type_name -> api.lists.list.v1alpha1.ListItem
	8,  // 5: api.lists.list.v1alpha1.UpdateListItemRequest.update_mask:type_name -> google.protobuf.FieldMask
	1,  // 6: api.lists.list.v1alpha1.ListItemService.CreateListItem:input_type -> api.lists.list.v1alpha1.CreateListItemRequest
	2,  // 7: api.lists.list.v1alpha1.ListItemService.ListListItems:input_type -> api.lists.list.v1alpha1.ListListItemsRequest
	4,  // 8: api.lists.list.v1alpha1.ListItemService.UpdateListItem:input_type -> api.lists.list.v1alpha1.UpdateListItemRequest
	5,  // 9: api.lists.list.v1alpha1.ListItemService.DeleteListItem:input_type -> api.lists.list.v1alpha1.DeleteListItemRequest
	6,  // 10: api.lists.list.v1alpha1.ListItemService.GetListItem:input_type -> api.lists.list.v1alpha1.GetListItemRequest
	0,  // 11: api.lists.list.v1alpha1.ListItemService.CreateListItem:output_type -> api.lists.list.v1alpha1.ListItem
	3,  // 12: api.lists.list.v1alpha1.ListItemService.ListListItems:output_type -> api.lists.list.v1alpha1.ListListItemsResponse
	0,  // 13: api.lists.list.v1alpha1.ListItemService.UpdateListItem:output_type -> api.lists.list.v1alpha1.ListItem
	0,  // 14: api.lists.list.v1alpha1.ListItemService.DeleteListItem:output_type -> api.lists.list.v1alpha1.ListItem
	0,  // 15: api.lists.list.v1alpha1.ListItemService.GetListItem:output_type -> api.lists.list.v1alpha1.ListItem
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_lists_list_v1alpha1_list_item_proto_init() }
func file_api_lists_list_v1alpha1_list_item_proto_init() {
	if File_api_lists_list_v1alpha1_list_item_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_lists_list_v1alpha1_list_item_proto_rawDesc), len(file_api_lists_list_v1alpha1_list_item_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_lists_list_v1alpha1_list_item_proto_goTypes,
		DependencyIndexes: file_api_lists_list_v1alpha1_list_item_proto_depIdxs,
		MessageInfos:      file_api_lists_list_v1alpha1_list_item_proto_msgTypes,
	}.Build()
	File_api_lists_list_v1alpha1_list_item_proto = out.File
	file_api_lists_list_v1alpha1_list_item_proto_goTypes = nil
	file_api_lists_list_v1alpha1_list_item_proto_depIdxs = nil
}
