// Code generated by protoc-gen-typescript-http. DO NOT EDIT.
/* eslint-disable camelcase */
// @ts-nocheck

// the main user calendar
export type Calendar = {
  // the name of the calendar
  //
  // Behaviors: IDENTIFIER
  name: string | undefined;
  // the title of the calendar
  //
  // Behaviors: REQUIRED
  title: string | undefined;
  // the description of the calendar
  //
  // Behaviors: OPTIONAL
  description: string | undefined;
  // the unique handle for the calendar (like a username, must be unique, user-friendly, and can be used for sharing)
  //
  // Behaviors: OPTIONAL
  handle: string | undefined;
  // the image url for the calendar
  //
  // Behaviors: OPTIONAL
  imageUri: string | undefined;
  // the visibility of the calendar
  //
  // Behaviors: REQUIRED
  visibility: apitypes_VisibilityLevel | undefined;
  // calendar access data
  //
  // Behaviors: OUTPUT_ONLY
  calendarAccess: Calendar_CalendarAccess | undefined;
};

// the visibility levels
export type apitypes_VisibilityLevel =
  // the visibility is not specified
  | "VISIBILITY_LEVEL_UNSPECIFIED"
  // the visibility is public
  | "VISIBILITY_LEVEL_PUBLIC"
  // the visibility is restricted
  | "VISIBILITY_LEVEL_RESTRICTED"
  // the visibility is private
  | "VISIBILITY_LEVEL_PRIVATE"
  // the visibility is hidden
  | "VISIBILITY_LEVEL_HIDDEN";
// the calendar access details
export type Calendar_CalendarAccess = {
  // the name of the calendar access
  //
  // Behaviors: OUTPUT_ONLY
  name: string | undefined;
  // the permission of the calendar
  //
  // Behaviors: OUTPUT_ONLY
  permissionLevel: apitypes_PermissionLevel | undefined;
  // the access state of the user to the calendar
  //
  // Behaviors: OUTPUT_ONLY
  state: apitypes_AccessState | undefined;
};

// the permission levels
export type apitypes_PermissionLevel =
  // the permission is not specified
  | "PERMISSION_LEVEL_UNSPECIFIED"
  // the permission is public
  | "PERMISSION_LEVEL_PUBLIC"
  // the permission is read
  | "PERMISSION_LEVEL_READ"
  // the permission is write
  | "PERMISSION_LEVEL_WRITE"
  // the permission is admin
  | "PERMISSION_LEVEL_ADMIN";
// the visibility levels
export type apitypes_AccessState =
  // This status should never get used.
  | "ACCESS_STATE_UNSPECIFIED"
  // The access is pending and can either be accepted or deleted.
  | "ACCESS_STATE_PENDING"
  // The access is accepted and can be deleted.
  | "ACCESS_STATE_ACCEPTED";
// the request to create a calendar
export type CreateCalendarRequest = {
  // the calendar to create
  //
  // Behaviors: REQUIRED
  calendar: Calendar | undefined;
  // the id of the calendar
  //
  // Behaviors: REQUIRED
  calendarId: string | undefined;
};

// the request to list calendars
export type ListCalendarsRequest = {
  // the parent of the calendars
  //
  // Behaviors: OPTIONAL
  parent: string | undefined;
  // the page size
  //
  // Behaviors: OPTIONAL
  pageSize: number | undefined;
  // the page token
  //
  // Behaviors: OPTIONAL
  pageToken: string | undefined;
  // used to specify the filter
  //
  // Behaviors: OPTIONAL
  filter: string | undefined;
};

// the response to list calendars
export type ListCalendarsResponse = {
  // the calendars
  calendars: Calendar[] | undefined;
  // the next page token
  nextPageToken: string | undefined;
};

// the request to update a calendar
export type UpdateCalendarRequest = {
  // the calendar to update
  //
  // Behaviors: REQUIRED
  calendar: Calendar | undefined;
  // the fields to update
  //
  // Behaviors: OPTIONAL
  updateMask: wellKnownFieldMask | undefined;
};

// In JSON, a field mask is encoded as a single string where paths are
// separated by a comma. Fields name in each path are converted
// to/from lower-camel naming conventions.
// As an example, consider the following message declarations:
//
//     message Profile {
//       User user = 1;
//       Photo photo = 2;
//     }
//     message User {
//       string display_name = 1;
//       string address = 2;
//     }
//
// In proto a field mask for `Profile` may look as such:
//
//     mask {
//       paths: "user.display_name"
//       paths: "photo"
//     }
//
// In JSON, the same mask is represented as below:
//
//     {
//       mask: "user.displayName,photo"
//     }
type wellKnownFieldMask = string;

// the request to delete a calendar
export type DeleteCalendarRequest = {
  // the name of the calendar
  //
  // Behaviors: REQUIRED
  name: string | undefined;
};

// the request to get a calendar
export type GetCalendarRequest = {
  // the name of the calendar
  //
  // Behaviors: REQUIRED
  name: string | undefined;
};

// the calendar service
export interface CalendarService {
  // create a calendar
  CreateCalendar(request: CreateCalendarRequest): Promise<Calendar>;
  // list calendars
  ListCalendars(request: ListCalendarsRequest): Promise<ListCalendarsResponse>;
  // update a calendar
  UpdateCalendar(request: UpdateCalendarRequest): Promise<Calendar>;
  // delete` a calendar
  DeleteCalendar(request: DeleteCalendarRequest): Promise<Calendar>;
  // get a calendar
  GetCalendar(request: GetCalendarRequest): Promise<Calendar>;
}

type RequestType = {
  path: string;
  method: string;
  body: string | null;
};

type RequestHandler = (request: RequestType, meta: { service: string, method: string }) => Promise<unknown>;

export function createCalendarServiceClient(
  handler: RequestHandler
): CalendarService {
  return {
    CreateCalendar(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      const path = `calendars/v1alpha1/calendars`; // eslint-disable-line quotes
      const body = JSON.stringify(request?.calendar ?? {});
      const queryParams: string[] = [];
      if (request.calendarId) {
        queryParams.push(`calendarId=${encodeURIComponent(request.calendarId.toString())}`)
      }
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "POST",
        body,
      }, {
        service: "CalendarService",
        method: "CreateCalendar",
      }) as Promise<Calendar>;
    },
    ListCalendars(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      const path = `calendars/v1alpha1/calendars`; // eslint-disable-line quotes
      const body = null;
      const queryParams: string[] = [];
      if (request.parent) {
        queryParams.push(`parent=${encodeURIComponent(request.parent.toString())}`)
      }
      if (request.pageSize) {
        queryParams.push(`pageSize=${encodeURIComponent(request.pageSize.toString())}`)
      }
      if (request.pageToken) {
        queryParams.push(`pageToken=${encodeURIComponent(request.pageToken.toString())}`)
      }
      if (request.filter) {
        queryParams.push(`filter=${encodeURIComponent(request.filter.toString())}`)
      }
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "GET",
        body,
      }, {
        service: "CalendarService",
        method: "ListCalendars",
      }) as Promise<ListCalendarsResponse>;
    },
    UpdateCalendar(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      if (!request.calendar?.name) {
        throw new Error("missing required field request.calendar.name");
      }
      const path = `calendars/v1alpha1/${request.calendar.name}`; // eslint-disable-line quotes
      const body = JSON.stringify(request?.calendar ?? {});
      const queryParams: string[] = [];
      if (request.updateMask) {
        queryParams.push(`updateMask=${encodeURIComponent(request.updateMask.toString())}`)
      }
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "PATCH",
        body,
      }, {
        service: "CalendarService",
        method: "UpdateCalendar",
      }) as Promise<Calendar>;
    },
    DeleteCalendar(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      if (!request.name) {
        throw new Error("missing required field request.name");
      }
      const path = `calendars/v1alpha1/${request.name}`; // eslint-disable-line quotes
      const body = null;
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "DELETE",
        body,
      }, {
        service: "CalendarService",
        method: "DeleteCalendar",
      }) as Promise<Calendar>;
    },
    GetCalendar(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      if (!request.name) {
        throw new Error("missing required field request.name");
      }
      const path = `calendars/v1alpha1/${request.name}`; // eslint-disable-line quotes
      const body = null;
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "GET",
        body,
      }, {
        service: "CalendarService",
        method: "GetCalendar",
      }) as Promise<Calendar>;
    },
  };
}
// This represents the data about a user's access to a calendar
export type Access = {
  // The name of the access
  //
  // Behaviors: IDENTIFIER
  name: string | undefined;
  // the name of the requesting user
  //
  // Behaviors: OUTPUT_ONLY
  requester: Access_Requester | undefined;
  // the name of the receiving user
  //
  // Behaviors: REQUIRED
  recipient: Access_User | undefined;
  // the permission level of the access
  //
  // Behaviors: REQUIRED
  level: apitypes_PermissionLevel | undefined;
  // the status of the access
  //
  // Behaviors: OUTPUT_ONLY
  state: apitypes_AccessState | undefined;
};

// the requester of the access
export type Access_Requester = {
  // the name of the user
  user?: string;
  // the name of the calendar
  calendar?: string;
};

// user data
export type Access_User = {
  // the name of the user
  //
  // Behaviors: REQUIRED
  name: string | undefined;
  // the username of the user
  //
  // Behaviors: OUTPUT_ONLY
  username: string | undefined;
  // the full name of the user
  //
  // Behaviors: OUTPUT_ONLY
  givenName: string | undefined;
  // the last name of the user
  //
  // Behaviors: OUTPUT_ONLY
  familyName: string | undefined;
};

// The request to create an access to a calendar
export type CreateAccessRequest = {
  // parent
  //
  // Behaviors: REQUIRED
  parent: string | undefined;
  // The access to create
  //
  // Behaviors: REQUIRED
  access: Access | undefined;
};

// The request to delete an access to a calendar
export type DeleteAccessRequest = {
  // name
  //
  // Behaviors: REQUIRED
  name: string | undefined;
};

// The request to get an access to a calendar
export type GetAccessRequest = {
  // name
  //
  // Behaviors: REQUIRED
  name: string | undefined;
};

// The request to list accesses to a calendar
export type ListAccessesRequest = {
  // parent
  //
  // Behaviors: REQUIRED
  parent: string | undefined;
  // The filter to apply to the list
  //
  // Behaviors: OPTIONAL
  filter: string | undefined;
  // The page size to apply to the list
  //
  // Behaviors: OPTIONAL
  pageSize: number | undefined;
  // The page token to apply to the list
  //
  // Behaviors: OPTIONAL
  pageToken: string | undefined;
};

// The response to list accesses to a calendar
export type ListAccessesResponse = {
  // The list of accesses
  accesses: Access[] | undefined;
  // The next page token
  nextPageToken: string | undefined;
};

// The request to update an access to a calendar
export type UpdateAccessRequest = {
  // access
  //
  // Behaviors: REQUIRED
  access: Access | undefined;
  // update mask
  //
  // Behaviors: OPTIONAL
  updateMask: wellKnownFieldMask | undefined;
};

// The request to accept an access to a calendar
export type AcceptAccessRequest = {
  // name
  //
  // Behaviors: REQUIRED
  name: string | undefined;
};

// The calendar recipient list service
export interface CalendarAccessService {
  // Create an access to a calendar
  CreateAccess(request: CreateAccessRequest): Promise<Access>;
  // Delete an access to a calendar
  DeleteAccess(request: DeleteAccessRequest): Promise<wellKnownEmpty>;
  // Get an access to a calendar
  GetAccess(request: GetAccessRequest): Promise<Access>;
  // List accesses to a calendar
  ListAccesses(request: ListAccessesRequest): Promise<ListAccessesResponse>;
  // Update an access to a calendar
  UpdateAccess(request: UpdateAccessRequest): Promise<Access>;
  // Accept a calendar access
  AcceptAccess(request: AcceptAccessRequest): Promise<Access>;
}

export function createCalendarAccessServiceClient(
  handler: RequestHandler
): CalendarAccessService {
  return {
    CreateAccess(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      if (!request.parent) {
        throw new Error("missing required field request.parent");
      }
      const path = `calendars/v1alpha1/${request.parent}/accesses`; // eslint-disable-line quotes
      const body = JSON.stringify(request?.access ?? {});
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "POST",
        body,
      }, {
        service: "CalendarAccessService",
        method: "CreateAccess",
      }) as Promise<Access>;
    },
    DeleteAccess(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      if (!request.name) {
        throw new Error("missing required field request.name");
      }
      const path = `calendars/v1alpha1/${request.name}`; // eslint-disable-line quotes
      const body = null;
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "DELETE",
        body,
      }, {
        service: "CalendarAccessService",
        method: "DeleteAccess",
      }) as Promise<wellKnownEmpty>;
    },
    GetAccess(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      if (!request.name) {
        throw new Error("missing required field request.name");
      }
      const path = `calendars/v1alpha1/${request.name}`; // eslint-disable-line quotes
      const body = null;
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "GET",
        body,
      }, {
        service: "CalendarAccessService",
        method: "GetAccess",
      }) as Promise<Access>;
    },
    ListAccesses(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      if (!request.parent) {
        throw new Error("missing required field request.parent");
      }
      const path = `calendars/v1alpha1/${request.parent}/accesses`; // eslint-disable-line quotes
      const body = null;
      const queryParams: string[] = [];
      if (request.filter) {
        queryParams.push(`filter=${encodeURIComponent(request.filter.toString())}`)
      }
      if (request.pageSize) {
        queryParams.push(`pageSize=${encodeURIComponent(request.pageSize.toString())}`)
      }
      if (request.pageToken) {
        queryParams.push(`pageToken=${encodeURIComponent(request.pageToken.toString())}`)
      }
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "GET",
        body,
      }, {
        service: "CalendarAccessService",
        method: "ListAccesses",
      }) as Promise<ListAccessesResponse>;
    },
    UpdateAccess(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      if (!request.access?.name) {
        throw new Error("missing required field request.access.name");
      }
      const path = `calendars/v1alpha1/${request.access.name}`; // eslint-disable-line quotes
      const body = JSON.stringify(request?.access ?? {});
      const queryParams: string[] = [];
      if (request.updateMask) {
        queryParams.push(`updateMask=${encodeURIComponent(request.updateMask.toString())}`)
      }
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "PATCH",
        body,
      }, {
        service: "CalendarAccessService",
        method: "UpdateAccess",
      }) as Promise<Access>;
    },
    AcceptAccess(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      if (!request.name) {
        throw new Error("missing required field request.name");
      }
      const path = `calendars/v1alpha1/${request.name}:accept`; // eslint-disable-line quotes
      const body = JSON.stringify(request);
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "POST",
        body,
      }, {
        service: "CalendarAccessService",
        method: "AcceptAccess",
      }) as Promise<Access>;
    },
  };
}
// An empty JSON object
type wellKnownEmpty = Record<never, never>;

// the main user event
export type Event = {
  // the name of the event
  //
  // Behaviors: IDENTIFIER
  name: string | undefined;
  // the title of the event
  //
  // Behaviors: REQUIRED
  title: string | undefined;
};

// the class of the event
export type Event_Class =
  // the class is unspecified
  | "CLASS_UNSPECIFIED"
  // the class is public
  | "CLASS_PUBLIC"
  // the class is private
  | "CLASS_PRIVATE"
  // the class is confidential
  | "CLASS_CONFIDENTIAL";
// the state of the event
export type Event_State =
  // the state is unspecified
  | "STATE_UNSPECIFIED"
  // the state is confirmed
  | "STATE_CONFIRMED"
  // the state is tentative
  | "STATE_TENTATIVE"
  // the state is cancelled
  | "STATE_CANCELLED";
// the event service
export interface EventService {
}

export function createEventServiceClient(
  handler: RequestHandler
): EventService {
  return {
  };
}

// @@protoc_insertion_point(typescript-http-eof)
