// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/meals/recipe/v1alpha1/recipe_recipient_list.proto

package recipev1alpha1

import (
	types "github.com/jcfug8/daylear/server/genapi/api/types"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The recipe recipient list resource
type RecipeRecipients struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the recipe recipient list
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The list of recipients
	Recipients    []*RecipeRecipients_Recipient `protobuf:"bytes,2,rep,name=recipients,proto3" json:"recipients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecipeRecipients) Reset() {
	*x = RecipeRecipients{}
	mi := &file_api_meals_recipe_v1alpha1_recipe_recipient_list_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecipeRecipients) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecipeRecipients) ProtoMessage() {}

func (x *RecipeRecipients) ProtoReflect() protoreflect.Message {
	mi := &file_api_meals_recipe_v1alpha1_recipe_recipient_list_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecipeRecipients.ProtoReflect.Descriptor instead.
func (*RecipeRecipients) Descriptor() ([]byte, []int) {
	return file_api_meals_recipe_v1alpha1_recipe_recipient_list_proto_rawDescGZIP(), []int{0}
}

func (x *RecipeRecipients) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RecipeRecipients) GetRecipients() []*RecipeRecipients_Recipient {
	if x != nil {
		return x.Recipients
	}
	return nil
}

// The request to get a recipe recipient list
type GetRecipeRecipientsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the recipe recipient list to get
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecipeRecipientsRequest) Reset() {
	*x = GetRecipeRecipientsRequest{}
	mi := &file_api_meals_recipe_v1alpha1_recipe_recipient_list_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecipeRecipientsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecipeRecipientsRequest) ProtoMessage() {}

func (x *GetRecipeRecipientsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_meals_recipe_v1alpha1_recipe_recipient_list_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecipeRecipientsRequest.ProtoReflect.Descriptor instead.
func (*GetRecipeRecipientsRequest) Descriptor() ([]byte, []int) {
	return file_api_meals_recipe_v1alpha1_recipe_recipient_list_proto_rawDescGZIP(), []int{1}
}

func (x *GetRecipeRecipientsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RecipeRecipients_Recipient struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the recipient
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// title of the recipient
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// The permission of the recipient
	Permission    types.PermissionLevel `protobuf:"varint,3,opt,name=permission,proto3,enum=api.types.PermissionLevel" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecipeRecipients_Recipient) Reset() {
	*x = RecipeRecipients_Recipient{}
	mi := &file_api_meals_recipe_v1alpha1_recipe_recipient_list_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecipeRecipients_Recipient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecipeRecipients_Recipient) ProtoMessage() {}

func (x *RecipeRecipients_Recipient) ProtoReflect() protoreflect.Message {
	mi := &file_api_meals_recipe_v1alpha1_recipe_recipient_list_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecipeRecipients_Recipient.ProtoReflect.Descriptor instead.
func (*RecipeRecipients_Recipient) Descriptor() ([]byte, []int) {
	return file_api_meals_recipe_v1alpha1_recipe_recipient_list_proto_rawDescGZIP(), []int{0, 0}
}

func (x *RecipeRecipients_Recipient) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RecipeRecipients_Recipient) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RecipeRecipients_Recipient) GetPermission() types.PermissionLevel {
	if x != nil {
		return x.Permission
	}
	return types.PermissionLevel(0)
}

var File_api_meals_recipe_v1alpha1_recipe_recipient_list_proto protoreflect.FileDescriptor

const file_api_meals_recipe_v1alpha1_recipe_recipient_list_proto_rawDesc = "" +
	"\n" +
	"5api/meals/recipe/v1alpha1/recipe_recipient_list.proto\x12\x19api.meals.recipe.v1alpha1\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a api/types/permission_level.proto\"\xab\x03\n" +
	"\x10RecipeRecipients\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\bR\x04name\x12Z\n" +
	"\n" +
	"recipients\x18\x02 \x03(\v25.api.meals.recipe.v1alpha1.RecipeRecipients.RecipientB\x03\xe0A\x03R\n" +
	"recipients\x1a\x80\x01\n" +
	"\tRecipient\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x03R\x04name\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tB\x03\xe0A\x03R\x05title\x12?\n" +
	"\n" +
	"permission\x18\x03 \x01(\x0e2\x1a.api.types.PermissionLevelB\x03\xe0A\x03R\n" +
	"permission:\x9e\x01\xeaA\x9a\x01\n" +
	"*api.meals.recipe.v1alpha1/RecipeRecipients\x12\x1brecipes/{recipe}/recipients\x12,circles/{circle}/recipes/{recipe}/recipients*\x10recipeRecipients2\x0frecipeRecipient\"d\n" +
	"\x1aGetRecipeRecipientsRequest\x12F\n" +
	"\x04name\x18\x01 \x01(\tB2\xe0A\x02\xfaA,\n" +
	"*api.meals.recipe.v1alpha1/RecipeRecipientsR\x04name2\x8a\x02\n" +
	"\x17RecipeRecipientsService\x12\xee\x01\n" +
	"\x13GetRecipeRecipients\x125.api.meals.recipe.v1alpha1.GetRecipeRecipientsRequest\x1a+.api.meals.recipe.v1alpha1.RecipeRecipients\"s\xdaA\x04name\x82\xd3\xe4\x93\x02fZ7\x125/meals/v1alpha1/{name=circles/*/recipes/*}/recipients\x12+/meals/v1alpha1/{name=recipes/*}/recipientsB\x92\x02\n" +
	"\x1dcom.api.meals.recipe.v1alpha1B\x18RecipeRecipientListProtoP\x01ZPgithub.com/jcfug8/daylear/server/genapi/api/meals/recipe/v1alpha1;recipev1alpha1\xa2\x02\x03AMR\xaa\x02\x19Api.Meals.Recipe.V1alpha1\xca\x02\x19Api\\Meals\\Recipe\\V1alpha1\xe2\x02%Api\\Meals\\Recipe\\V1alpha1\\GPBMetadata\xea\x02\x1cApi::Meals::Recipe::V1alpha1b\x06proto3"

var (
	file_api_meals_recipe_v1alpha1_recipe_recipient_list_proto_rawDescOnce sync.Once
	file_api_meals_recipe_v1alpha1_recipe_recipient_list_proto_rawDescData []byte
)

func file_api_meals_recipe_v1alpha1_recipe_recipient_list_proto_rawDescGZIP() []byte {
	file_api_meals_recipe_v1alpha1_recipe_recipient_list_proto_rawDescOnce.Do(func() {
		file_api_meals_recipe_v1alpha1_recipe_recipient_list_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_meals_recipe_v1alpha1_recipe_recipient_list_proto_rawDesc), len(file_api_meals_recipe_v1alpha1_recipe_recipient_list_proto_rawDesc)))
	})
	return file_api_meals_recipe_v1alpha1_recipe_recipient_list_proto_rawDescData
}

var file_api_meals_recipe_v1alpha1_recipe_recipient_list_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_meals_recipe_v1alpha1_recipe_recipient_list_proto_goTypes = []any{
	(*RecipeRecipients)(nil),           // 0: api.meals.recipe.v1alpha1.RecipeRecipients
	(*GetRecipeRecipientsRequest)(nil), // 1: api.meals.recipe.v1alpha1.GetRecipeRecipientsRequest
	(*RecipeRecipients_Recipient)(nil), // 2: api.meals.recipe.v1alpha1.RecipeRecipients.Recipient
	(types.PermissionLevel)(0),         // 3: api.types.PermissionLevel
}
var file_api_meals_recipe_v1alpha1_recipe_recipient_list_proto_depIdxs = []int32{
	2, // 0: api.meals.recipe.v1alpha1.RecipeRecipients.recipients:type_name -> api.meals.recipe.v1alpha1.RecipeRecipients.Recipient
	3, // 1: api.meals.recipe.v1alpha1.RecipeRecipients.Recipient.permission:type_name -> api.types.PermissionLevel
	1, // 2: api.meals.recipe.v1alpha1.RecipeRecipientsService.GetRecipeRecipients:input_type -> api.meals.recipe.v1alpha1.GetRecipeRecipientsRequest
	0, // 3: api.meals.recipe.v1alpha1.RecipeRecipientsService.GetRecipeRecipients:output_type -> api.meals.recipe.v1alpha1.RecipeRecipients
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_meals_recipe_v1alpha1_recipe_recipient_list_proto_init() }
func file_api_meals_recipe_v1alpha1_recipe_recipient_list_proto_init() {
	if File_api_meals_recipe_v1alpha1_recipe_recipient_list_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_meals_recipe_v1alpha1_recipe_recipient_list_proto_rawDesc), len(file_api_meals_recipe_v1alpha1_recipe_recipient_list_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_meals_recipe_v1alpha1_recipe_recipient_list_proto_goTypes,
		DependencyIndexes: file_api_meals_recipe_v1alpha1_recipe_recipient_list_proto_depIdxs,
		MessageInfos:      file_api_meals_recipe_v1alpha1_recipe_recipient_list_proto_msgTypes,
	}.Build()
	File_api_meals_recipe_v1alpha1_recipe_recipient_list_proto = out.File
	file_api_meals_recipe_v1alpha1_recipe_recipient_list_proto_goTypes = nil
	file_api_meals_recipe_v1alpha1_recipe_recipient_list_proto_depIdxs = nil
}
