// Code generated by protoc-gen-typescript-http. DO NOT EDIT.
/* eslint-disable camelcase */
// @ts-nocheck

// the main user circle
export type Circle = {
  // the name of the circle
  //
  // Behaviors: IDENTIFIER
  name: string | undefined;
  // the title of the circle
  //
  // Behaviors: REQUIRED
  title: string | undefined;
};


// @@protoc_insertion_point(typescript-http-eof)
