name: Deploy to DigitalOcean App Platform

on:
  workflow_run:
    workflows: ["Prod Client Build and Deploy", "Prod Server Build and Deploy"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DigitalOcean App Platform
        uses: digitalocean/app_action/deploy@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}
          app_name: daylear 