name: Prod Client Build and Deploy
on:
  push:
    tags:
      - 'v*'
jobs:
  prod_build_ui:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    defaults:
      run:
        working-directory: client
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Sanitize GitHub ref for Docker tag
      id: sanitize
      run: echo "SANITIZED_REF=${GITHUB_REF#refs/tags/}" | sed 's/\./_/g' >> $GITHUB_ENV

    - name: Log in to the Container registry
      uses: docker/login-action@v3.3.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v6.5.0
      with:
        context: ./client
        push: true
        tags: |
          ghcr.io/jcfug8/daylear-client:latest
          ghcr.io/jcfug8/daylear-client:${{ env.SANITIZED_REF }}