name: Prod Build and Deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  build_client:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    defaults:
      run:
        working-directory: client
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sanitize GitHub ref for Docker tag
        id: sanitize
        run: echo "SANITIZED_REF=${GITHUB_REF#refs/tags/}" | sed 's/\./_/g' >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.5.0
        with:
          context: ./client
          push: true
          tags: |
            ghcr.io/jcfug8/daylear-client:latest
            ghcr.io/jcfug8/daylear-client:${{ env.SANITIZED_REF }}

  build_server:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    defaults:
      run:
        working-directory: server
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sanitize GitHub ref for Docker tag
        id: sanitize
        run: echo "SANITIZED_REF=${GITHUB_REF#refs/tags/}" | sed 's/\./_/g' >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.5.0
        with:
          context: server
          push: true
          tags: |
            ghcr.io/jcfug8/daylear:latest
            ghcr.io/jcfug8/daylear:${{ env.SANITIZED_REF }}

  deploy:
    runs-on: ubuntu-latest
    needs: [build_client, build_server]
    steps:
      - name: Deploy to DigitalOcean App Platform
        uses: digitalocean/app_action/deploy@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}
          app_name: daylear 